In [1]:
import requests
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import time
from selenium import webdriver

In [2]:
driver=webdriver.Chrome(executable_path="C:\Driver\chromedriver_win32 (3)\chromedriver.exe")
driver.get("https://www.acquisitions.global/members")
driver.maximize_window()

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1835009392.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(executable_path="C:\Driver\chromedriver_win32 (3)\chromedriver.exe")

In [5]:
from selenium.webdriver.common.keys import Keys
def scroll_down():
    # Scroll down to the bottom of the page
    driver.find_element(By.TAG_NAME,'body').send_keys(Keys.END)
    time.sleep(2)  # Adjust the sleep duration as needed

# Scroll down repeatedly until reaching the bottom of the page
while True:
    # Scroll down
    scroll_down()
    
    # Check if the bottom of the page has been reached
    page_height = driver.execute_script("return document.body.scrollHeight")
    window_height = driver.execute_script("return window.innerHeight")
    if page_height == window_height:
        break

# Close the WebDriver
driver.quit()

KeyboardInterrupt:

In [102]:
bx=driver.find_element(By.CSS_SELECTOR,"#content-region > div > div.list-region > div > ul")

In [103]:
box=bx.find_elements(By.TAG_NAME,"li")

In [105]:
len(box)

832

In [98]:
import pandas as pd
Dic= {}
gc= pd.DataFrame(data=Dic,index=[0],columns=["Full name","First Name","Last Name",'Industry','Title','About','Location','Intro','personal web','Linked in'])

In [104]:

for z in range(633,len(box)):
    industry=''
    try:
        location=box[z].find_element(By.CSS_SELECTOR,'[class="member-list-item-location text-color-lighter"]').text
    except:
        location="NA"
    title=box[z].find_element(By.CSS_SELECTOR,'[class="mighty-attribution-badge theme-color-link-text-link navigate"]').text
    box[z].find_element(By.TAG_NAME,"a").click()
    time.sleep(10)
    try:
        name=driver.find_element(By.TAG_NAME,"h1").text
    except:
        continue
    first_name=name.split()[0]
    last_name=name.split()[-1]
    try:
        first_ele=driver.find_element(By.CSS_SELECTOR,'#community-member-about > div:nth-child(3) > div > div.title').text
    except:
        first_ele="NA"

    if first_ele=="Industry":
        industry=driver.find_element(By.CSS_SELECTOR,'#community-member-about > div:nth-child(3) > div > div.content > a').text
    try:
        snd_ele=driver.find_element(By.CSS_SELECTOR,'#community-member-about > div:nth-child(2) > div > div.title').text
    except:
        snd_ele="NA"
    
    if snd_ele=="Industry":
        industry=driver.find_element(By.CSS_SELECTOR,'#community-member-about > div:nth-child(2) > div > div.content > a').text
    
    try:
        about=driver.find_element(By.CSS_SELECTOR,"#community-member-about > div:nth-child(1) > div > div.content").text
    except:
        about="NA"
    try:
        intro=driver.find_element(By.CSS_SELECTOR,'[class="description text-color-body"]').text
    except:
        intro="NA"
    try:
        per_web=driver.find_element(By.CSS_SELECTOR,'[id="personal-links-region"]').find_element(By.TAG_NAME,"a").get_attribute("href")
    except:
        per_web="NA"
    try:
        linked=driver.find_element(By.CSS_SELECTOR,'[data-original-title="Linkedin"]').get_attribute("href")
    except:
        linked="NA"
    if per_web==linked:
        per_web="NA"
    Dic={"Full name":name,"First Name":first_name,"Last Name":last_name,'Industry':industry,'Title':title,'About':about,'Location':location,'Intro':intro,'personal web':per_web,'Linked in':linked}
    gc= gc.append(Dic, ignore_index=True)
    driver.find_element(By.CSS_SELECTOR,'[data-title="Close"]').click()
    time.sleep(2)
    print(gc)

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
630        Pluri Castaneda      Pluri     Castaneda               Member
631            Mark Binnie       Mark        Binnie               Member
632           Justin Faust     Justin         Faust               Member
633           Oladele Dina    Oladele          Dina               Member
634       Lorena Cervantes     Lorena     Cervantes               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
630                                                                     NA
631                                                                     NA
632                                                           Mesquite, TX
633                                                                     NA
634                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
630                                                 NA
631                                                 NA
632                                                 NA
633                                                 NA
634                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
630                                  NA
631                                  NA
632                                  NA
633                                  NA
634                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
630                                                 NA
631                                                 NA
632                                                 NA
633                                                 NA
634                                                 NA

[635 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
631            Mark Binnie       Mark        Binnie               Member
632           Justin Faust     Justin         Faust               Member
633           Oladele Dina    Oladele          Dina               Member
634       Lorena Cervantes     Lorena     Cervantes               Member
635          Jerret Turner     Jerret        Turner               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
631                                                                     NA
632                                                           Mesquite, TX
633                                                                     NA
634                                                                     NA
635                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
631                                                 NA
632                                                 NA
633                                                 NA
634                                                 NA
635                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
631                                  NA
632                                  NA
633                                  NA
634                                  NA
635                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
631                                                 NA
632                                                 NA
633                                                 NA
634                                                 NA
635                                                 NA

[636 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
632           Justin Faust     Justin         Faust               Member
633           Oladele Dina    Oladele          Dina               Member
634       Lorena Cervantes     Lorena     Cervantes               Member
635          Jerret Turner     Jerret        Turner               Member
636         Randy McKinley      Randy      McKinley   Consulting  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
632                                                           Mesquite, TX
633                                                                     NA
634                                                                     NA
635                                                                     NA
636                                                         Washington, DC

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
632                                                 NA
633                                                 NA
634                                                 NA
635                                                 NA
636                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
632                                  NA
633                                  NA
634                                  NA
635                                  NA
636                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
632                                                 NA
633                                                 NA
634                                                 NA
635                                                 NA
636                                                 NA

[637 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
633           Oladele Dina    Oladele          Dina               Member
634       Lorena Cervantes     Lorena     Cervantes               Member
635          Jerret Turner     Jerret        Turner               Member
636         Randy McKinley      Randy      McKinley   Consulting  Member
637          saul portillo       saul      portillo   Technology  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
633                                                                     NA
634                                                                     NA
635                                                                     NA
636                                                         Washington, DC
637  My goals are to be an investor, as of right no...           Boise, ID

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
633                                                 NA
634                                                 NA
635                                                 NA
636                                                 NA
637  I have work in the restaurant business for 10 ...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
633                                  NA
634                                  NA
635                                  NA
636                                  NA
637                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
633                                                 NA
634                                                 NA
635                                                 NA
636                                                 NA
637                                                 NA

[638 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
634       Lorena Cervantes     Lorena     Cervantes               Member
635          Jerret Turner     Jerret        Turner               Member
636         Randy McKinley      Randy      McKinley   Consulting  Member
637          saul portillo       saul      portillo   Technology  Member
638     Nicholas McPherson   Nicholas     McPherson               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
634                                                                     NA
635                                                                     NA
636                                                         Washington, DC
637  My goals are to be an investor, as of right no...           Boise, ID
638                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
634                                                 NA
635                                                 NA
636                                                 NA
637  I have work in the restaurant business for 10 ...
638                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
634                                  NA
635                                  NA
636                                  NA
637                                  NA
638                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
634                                                 NA
635                                                 NA
636                                                 NA
637                                                 NA
638                                                 NA

[639 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
635          Jerret Turner     Jerret        Turner               Member
636         Randy McKinley      Randy      McKinley   Consulting  Member
637          saul portillo       saul      portillo   Technology  Member
638     Nicholas McPherson   Nicholas     McPherson               Member
639            derek laing      derek         laing               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
635                                                                     NA
636                                                         Washington, DC
637  My goals are to be an investor, as of right no...           Boise, ID
638                                                                     NA
639                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
635                                                 NA
636                                                 NA
637  I have work in the restaurant business for 10 ...
638                                                 NA
639                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
635                                  NA
636                                  NA
637                                  NA
638                                  NA
639                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
635                                                 NA
636                                                 NA
637                                                 NA
638                                                 NA
639                                                 NA

[640 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
636         Randy McKinley      Randy      McKinley     Consulting  Member
637          saul portillo       saul      portillo     Technology  Member
638     Nicholas McPherson   Nicholas     McPherson                 Member
639            derek laing      derek         laing                 Member
640           Eric Ficinus       Eric       Ficinus  Manufacturing  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
636                                                         Washington, DC
637  My goals are to be an investor, as of right no...           Boise, ID
638                                                                     NA
639                                                                     NA
640                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
636                                                 NA
637  I have work in the restaurant business for 10 ...
638                                                 NA
639                                                 NA
640  Passionate visionary with a design background ...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
636                                  NA
637                                  NA
638                                  NA
639                                  NA
640         http://www.ericficinus.com/

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
636                                                 NA
637                                                 NA
638                                                 NA
639                                                 NA
640                                                 NA

[641 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
637          saul portillo       saul      portillo     Technology  Member
638     Nicholas McPherson   Nicholas     McPherson                 Member
639            derek laing      derek         laing                 Member
640           Eric Ficinus       Eric       Ficinus  Manufacturing  Member
641           Frank Harris      Frank        Harris       Medicine  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
637  My goals are to be an investor, as of right no...           Boise, ID
638                                                                     NA
639                                                                     NA
640                                                                     NA
641                                                         Cincinnati, OH

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
637  I have work in the restaurant business for 10 ...
638                                                 NA
639                                                 NA
640  Passionate visionary with a design background ...
641  In Medicine. Open to industries outside of my ...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
637                                  NA
638                                  NA
639                                  NA
640         http://www.ericficinus.com/
641                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
637                                                 NA
638                                                 NA
639                                                 NA
640                                                 NA
641                                                 NA

[642 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
638     Nicholas McPherson   Nicholas     McPherson                 Member
639            derek laing      derek         laing                 Member
640           Eric Ficinus       Eric       Ficinus  Manufacturing  Member
641           Frank Harris      Frank        Harris       Medicine  Member
642          Tyrone Auston     Tyrone        Auston   Construction  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
638                                                                     NA
639                                                                     NA
640                                                                     NA
641                                                         Cincinnati, OH
642  looking forward to joining the journey with ot...     Los Angeles, CA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
638                                                 NA
639                                                 NA
640  Passionate visionary with a design background ...
641  In Medicine. Open to industries outside of my ...
642  I've been in the construction industry for mos...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
638                                  NA
639                                  NA
640         http://www.ericficinus.com/
641                                  NA
642                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
638                                                 NA
639                                                 NA
640                                                 NA
641                                                 NA
642                                                 NA

[643 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
639            derek laing      derek         laing                 Member
640           Eric Ficinus       Eric       Ficinus  Manufacturing  Member
641           Frank Harris      Frank        Harris       Medicine  Member
642          Tyrone Auston     Tyrone        Auston   Construction  Member
643       David McClements      David    McClements                 Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
639                                                                     NA
640                                                                     NA
641                                                         Cincinnati, OH
642  looking forward to joining the journey with ot...     Los Angeles, CA
643                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
639                                                 NA
640  Passionate visionary with a design background ...
641  In Medicine. Open to industries outside of my ...
642  I've been in the construction industry for mos...
643                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
639                                  NA
640         http://www.ericficinus.com/
641                                  NA
642                                  NA
643                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
639                                                 NA
640                                                 NA
641                                                 NA
642                                                 NA
643                                                 NA

[644 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
640           Eric Ficinus       Eric       Ficinus  Manufacturing  Member
641           Frank Harris      Frank        Harris       Medicine  Member
642          Tyrone Auston     Tyrone        Auston   Construction  Member
643       David McClements      David    McClements                 Member
644            Herman Post     Herman          Post   Construction  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
640                                                                     NA
641                                                         Cincinnati, OH
642  looking forward to joining the journey with ot...     Los Angeles, CA
643                                                                     NA
644                                                         Guelph, Canada

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
640  Passionate visionary with a design background ...
641  In Medicine. Open to industries outside of my ...
642  I've been in the construction industry for mos...
643                                                 NA
644                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
640         http://www.ericficinus.com/
641                                  NA
642                                  NA
643                                  NA
644                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
640                                                 NA
641                                                 NA
642                                                 NA
643                                                 NA
644  https://www.linkedin.com/in/herman-post-70113320/

[645 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
641           Frank Harris      Frank        Harris      Medicine  Member
642          Tyrone Auston     Tyrone        Auston  Construction  Member
643       David McClements      David    McClements                Member
644            Herman Post     Herman          Post  Construction  Member
645            Tamra Ellis      Tamra         Ellis                Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
641                                                         Cincinnati, OH
642  looking forward to joining the journey with ot...     Los Angeles, CA
643                                                                     NA
644                                                         Guelph, Canada
645                                                        Toronto, Canada

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
641  In Medicine. Open to industries outside of my ...
642  I've been in the construction industry for mos...
643                                                 NA
644                                                 NA
645                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
641                                  NA
642                                  NA
643                                  NA
644                                  NA
645                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
641                                                 NA
642                                                 NA
643                                                 NA
644  https://www.linkedin.com/in/herman-post-70113320/
645                                                 NA

[646 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
642          Tyrone Auston     Tyrone        Auston  Construction  Member
643       David McClements      David    McClements                Member
644            Herman Post     Herman          Post  Construction  Member
645            Tamra Ellis      Tamra         Ellis                Member
646           Vuk Cobeljic        Vuk      Cobeljic                Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
642  looking forward to joining the journey with ot...     Los Angeles, CA
643                                                                     NA
644                                                         Guelph, Canada
645                                                        Toronto, Canada
646                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
642  I've been in the construction industry for mos...
643                                                 NA
644                                                 NA
645                                                 NA
646                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
642                                  NA
643                                  NA
644                                  NA
645                                  NA
646                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
642                                                 NA
643                                                 NA
644  https://www.linkedin.com/in/herman-post-70113320/
645                                                 NA
646                                                 NA

[647 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
643       David McClements      David    McClements                Member
644            Herman Post     Herman          Post  Construction  Member
645            Tamra Ellis      Tamra         Ellis                Member
646           Vuk Cobeljic        Vuk      Cobeljic                Member
647        Shawn Garnuette      Shawn     Garnuette                Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
643
644
645
646
647

                        Location  \
0                            NaN
1                     Marion, TX
2                             NA
3              San Francisco, CA
4             Boisbriand, Canada
..                           ...
643                           NA
644               Guelph, Canada
645              Toronto, Canada
646                           NA
647  Lei Ke Ya Nei Zhen, Iceland

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
643                                                 NA
644                                                 NA
645                                                 NA
646                                                 NA
647                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
643                                  NA
644                                  NA
645                                  NA
646                                  NA
647                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
643                                                 NA
644  https://www.linkedin.com/in/herman-post-70113320/
645                                                 NA
646                                                 NA
647                                                 NA

[648 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
644            Herman Post     Herman          Post  Construction  Member
645            Tamra Ellis      Tamra         Ellis                Member
646           Vuk Cobeljic        Vuk      Cobeljic                Member
647        Shawn Garnuette      Shawn     Garnuette                Member
648           Mishay Kelly     Mishay         Kelly                Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
644
645
646
647
648

                        Location  \
0                            NaN
1                     Marion, TX
2                             NA
3              San Francisco, CA
4             Boisbriand, Canada
..                           ...
644               Guelph, Canada
645              Toronto, Canada
646                           NA
647  Lei Ke Ya Nei Zhen, Iceland
648                           NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
644                                                 NA
645                                                 NA
646                                                 NA
647                                                 NA
648                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
644                                  NA
645                                  NA
646                                  NA
647                                  NA
648                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
644  https://www.linkedin.com/in/herman-post-70113320/
645                                                 NA
646                                                 NA
647                                                 NA
648                                                 NA

[649 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
645            Tamra Ellis      Tamra         Ellis               Member
646           Vuk Cobeljic        Vuk      Cobeljic               Member
647        Shawn Garnuette      Shawn     Garnuette               Member
648           Mishay Kelly     Mishay         Kelly               Member
649         Stefan DeSalle     Stefan       DeSalle               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
645
646
647
648
649

                        Location  \
0                            NaN
1                     Marion, TX
2                             NA
3              San Francisco, CA
4             Boisbriand, Canada
..                           ...
645              Toronto, Canada
646                           NA
647  Lei Ke Ya Nei Zhen, Iceland
648                           NA
649                           NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
645                                                 NA
646                                                 NA
647                                                 NA
648                                                 NA
649                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
645                                  NA
646                                  NA
647                                  NA
648                                  NA
649                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
645                                                 NA
646                                                 NA
647                                                 NA
648                                                 NA
649                                                 NA

[650 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
646           Vuk Cobeljic        Vuk      Cobeljic               Member
647        Shawn Garnuette      Shawn     Garnuette               Member
648           Mishay Kelly     Mishay         Kelly               Member
649         Stefan DeSalle     Stefan       DeSalle               Member
650           Chris Dobson      Chris        Dobson   Technology  Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
646
647
648
649
650

                        Location  \
0                            NaN
1                     Marion, TX
2                             NA
3              San Francisco, CA
4             Boisbriand, Canada
..                           ...
646                           NA
647  Lei Ke Ya Nei Zhen, Iceland
648                           NA
649                           NA
650                           NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
646                                                 NA
647                                                 NA
648                                                 NA
649                                                 NA
650                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
646                                  NA
647                                  NA
648                                  NA
649                                  NA
650                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
646                                                 NA
647                                                 NA
648                                                 NA
649                                                 NA
650                                                 NA

[651 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
647        Shawn Garnuette      Shawn     Garnuette               Member
648           Mishay Kelly     Mishay         Kelly               Member
649         Stefan DeSalle     Stefan       DeSalle               Member
650           Chris Dobson      Chris        Dobson   Technology  Member
651         Mohammed Islam   Mohammed         Islam               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
647
648
649
650
651

                        Location  \
0                            NaN
1                     Marion, TX
2                             NA
3              San Francisco, CA
4             Boisbriand, Canada
..                           ...
647  Lei Ke Ya Nei Zhen, Iceland
648                           NA
649                           NA
650                           NA
651                           NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
647                                                 NA
648                                                 NA
649                                                 NA
650                                                 NA
651                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
647                                  NA
648                                  NA
649                                  NA
650                                  NA
651                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
647                                                 NA
648                                                 NA
649                                                 NA
650                                                 NA
651                                                 NA

[652 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
648           Mishay Kelly     Mishay         Kelly               Member
649         Stefan DeSalle     Stefan       DeSalle               Member
650           Chris Dobson      Chris        Dobson   Technology  Member
651         Mohammed Islam   Mohammed         Islam               Member
652        Teodor Gavrilov     Teodor      Gavrilov               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
648                                                                     NA
649                                                                     NA
650                                                                     NA
651                                                                     NA
652                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
648                                                 NA
649                                                 NA
650                                                 NA
651                                                 NA
652                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
648                                  NA
649                                  NA
650                                  NA
651                                  NA
652                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
648                                                 NA
649                                                 NA
650                                                 NA
651                                                 NA
652                                                 NA

[653 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
649         Stefan DeSalle     Stefan       DeSalle               Member
650           Chris Dobson      Chris        Dobson   Technology  Member
651         Mohammed Islam   Mohammed         Islam               Member
652        Teodor Gavrilov     Teodor      Gavrilov               Member
653        Mohamed Plaisir    Mohamed       Plaisir               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
649                                                                     NA
650                                                                     NA
651                                                                     NA
652                                                                     NA
653                                                            Orlando, FL

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
649                                                 NA
650                                                 NA
651                                                 NA
652                                                 NA
653                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
649                                  NA
650                                  NA
651                                  NA
652                                  NA
653                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
649                                                 NA
650                                                 NA
651                                                 NA
652                                                 NA
653                                                 NA

[654 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
650           Chris Dobson      Chris        Dobson   Technology  Member
651         Mohammed Islam   Mohammed         Islam               Member
652        Teodor Gavrilov     Teodor      Gavrilov               Member
653        Mohamed Plaisir    Mohamed       Plaisir               Member
654           George Ayres     George         Ayres               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
650                                                                     NA
651                                                                     NA
652                                                                     NA
653                                                            Orlando, FL
654                                                         Washington, DC

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
650                                                 NA
651                                                 NA
652                                                 NA
653                                                 NA
654                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
650                                  NA
651                                  NA
652                                  NA
653                                  NA
654                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
650                                                 NA
651                                                 NA
652                                                 NA
653                                                 NA
654                                                 NA

[655 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
651         Mohammed Islam   Mohammed         Islam               Member
652        Teodor Gavrilov     Teodor      Gavrilov               Member
653        Mohamed Plaisir    Mohamed       Plaisir               Member
654           George Ayres     George         Ayres               Member
655          Joseph Baikie     Joseph        Baikie               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
651                                                                     NA
652                                                                     NA
653                                                            Orlando, FL
654                                                         Washington, DC
655                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
651                                                 NA
652                                                 NA
653                                                 NA
654                                                 NA
655                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
651                                  NA
652                                  NA
653                                  NA
654                                  NA
655                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
651                                                 NA
652                                                 NA
653                                                 NA
654                                                 NA
655                                                 NA

[656 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
652        Teodor Gavrilov     Teodor      Gavrilov               Member
653        Mohamed Plaisir    Mohamed       Plaisir               Member
654           George Ayres     George         Ayres               Member
655          Joseph Baikie     Joseph        Baikie               Member
656         Winston Foster    Winston        Foster               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
652                                                                     NA
653                                                            Orlando, FL
654                                                         Washington, DC
655                                                                     NA
656                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
652                                                 NA
653                                                 NA
654                                                 NA
655                                                 NA
656                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
652                                  NA
653                                  NA
654                                  NA
655                                  NA
656                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
652                                                 NA
653                                                 NA
654                                                 NA
655                                                 NA
656                                                 NA

[657 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
653        Mohamed Plaisir    Mohamed       Plaisir               Member
654           George Ayres     George         Ayres               Member
655          Joseph Baikie     Joseph        Baikie               Member
656         Winston Foster    Winston        Foster               Member
657            James Owens      James         Owens               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
653                                                            Orlando, FL
654                                                         Washington, DC
655                                                                     NA
656                                                                     NA
657                                                          Las Vegas, NV

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
653                                                 NA
654                                                 NA
655                                                 NA
656                                                 NA
657                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
653                                  NA
654                                  NA
655                                  NA
656                                  NA
657                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
653                                                 NA
654                                                 NA
655                                                 NA
656                                                 NA
657                                                 NA

[658 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
654           George Ayres     George         Ayres               Member
655          Joseph Baikie     Joseph        Baikie               Member
656         Winston Foster    Winston        Foster               Member
657            James Owens      James         Owens               Member
658          Dario Bucceri      Dario       Bucceri               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
654
655
656
657
658

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
654           Washington, DC
655                       NA
656                       NA
657            Las Vegas, NV
658  Ashford, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
654                                                 NA
655                                                 NA
656                                                 NA
657                                                 NA
658                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
654                                  NA
655                                  NA
656                                  NA
657                                  NA
658                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
654                                                 NA
655                                                 NA
656                                                 NA
657                                                 NA
658                                                 NA

[659 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
655          Joseph Baikie     Joseph        Baikie               Member
656         Winston Foster    Winston        Foster               Member
657            James Owens      James         Owens               Member
658          Dario Bucceri      Dario       Bucceri               Member
659            Tyson Brown      Tyson         Brown               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
655
656
657
658
659

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
655                       NA
656                       NA
657            Las Vegas, NV
658  Ashford, United Kingdom
659     Melbourne, Australia

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
655                                                 NA
656                                                 NA
657                                                 NA
658                                                 NA
659                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
655                                  NA
656                                  NA
657                                  NA
658                                  NA
659                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
655                                                 NA
656                                                 NA
657                                                 NA
658                                                 NA
659                                                 NA

[660 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
656         Winston Foster    Winston        Foster               Member
657            James Owens      James         Owens               Member
658          Dario Bucceri      Dario       Bucceri               Member
659            Tyson Brown      Tyson         Brown               Member
660            Maros Feher      Maros         Feher               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
656
657
658
659
660

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
656                       NA
657            Las Vegas, NV
658  Ashford, United Kingdom
659     Melbourne, Australia
660                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
656                                                 NA
657                                                 NA
658                                                 NA
659                                                 NA
660                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
656                                  NA
657                                  NA
658                                  NA
659                                  NA
660                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
656                                                 NA
657                                                 NA
658                                                 NA
659                                                 NA
660                                                 NA

[661 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name  First Name     Last Name     Industry   Title  \
0                      NaN         NaN           NaN          NaN     NaN
1                 Angela P      Angela             P  Photography    Host
2    Kanhnika Khanthavixay    Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela        Friz           Ela               Member
4           Pascal Germain      Pascal       Germain   Technology  Member
..                     ...         ...           ...          ...     ...
657            James Owens       James         Owens               Member
658          Dario Bucceri       Dario       Bucceri               Member
659            Tyson Brown       Tyson         Brown               Member
660            Maros Feher       Maros         Feher               Member
661        Barrington Edie  Barrington          Edie               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
657
658
659
660
661

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
657            Las Vegas, NV
658  Ashford, United Kingdom
659     Melbourne, Australia
660                       NA
661                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
657                                                 NA
658                                                 NA
659                                                 NA
660                                                 NA
661                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
657                                  NA
658                                  NA
659                                  NA
660                                  NA
661                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
657                                                 NA
658                                                 NA
659                                                 NA
660                                                 NA
661                                                 NA

[662 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name  First Name     Last Name         Industry   Title  \
0                      NaN         NaN           NaN              NaN     NaN
1                 Angela P      Angela             P      Photography    Host
2    Kanhnika Khanthavixay    Kanhnika  Khanthavixay       Technology  Member
3                 Friz Ela        Friz           Ela                   Member
4           Pascal Germain      Pascal       Germain       Technology  Member
..                     ...         ...           ...              ...     ...
658          Dario Bucceri       Dario       Bucceri                   Member
659            Tyson Brown       Tyson         Brown                   Member
660            Maros Feher       Maros         Feher                   Member
661        Barrington Edie  Barrington          Edie                   Member
662          Matthew Haupt     Matthew         Haupt  Tax and Finance  Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
658
659
660
661
662

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
658  Ashford, United Kingdom
659     Melbourne, Australia
660                       NA
661                       NA
662              Houston, TX

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
658                                                 NA
659                                                 NA
660                                                 NA
661                                                 NA
662  Currently a tax professional, getting out of t...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
658                                  NA
659                                  NA
660                                  NA
661                                  NA
662                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
658                                                 NA
659                                                 NA
660                                                 NA
661                                                 NA
662                                                 NA

[663 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name  First Name     Last Name         Industry   Title  \
0                      NaN         NaN           NaN              NaN     NaN
1                 Angela P      Angela             P      Photography    Host
2    Kanhnika Khanthavixay    Kanhnika  Khanthavixay       Technology  Member
3                 Friz Ela        Friz           Ela                   Member
4           Pascal Germain      Pascal       Germain       Technology  Member
..                     ...         ...           ...              ...     ...
659            Tyson Brown       Tyson         Brown                   Member
660            Maros Feher       Maros         Feher                   Member
661        Barrington Edie  Barrington          Edie                   Member
662          Matthew Haupt     Matthew         Haupt  Tax and Finance  Member
663              Rits Ritz        Rits          Ritz       Consulting  Member

                                                 About              Location  \
0                                                  NaN                   NaN
1    l'm Angela and here to help you succeed. l am ...            Marion, TX
2    I have over 15+ years in project management. I...                    NA
3        I'm part of the team here at Acquisitions.com     San Francisco, CA
4    25+ years of expertise as business owner Most ...    Boisbriand, Canada
..                                                 ...                   ...
659                                                     Melbourne, Australia
660                                                                       NA
661                                                                       NA
662                                                              Houston, TX
663                                                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
659                                                 NA
660                                                 NA
661                                                 NA
662  Currently a tax professional, getting out of t...
663                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
659                                  NA
660                                  NA
661                                  NA
662                                  NA
663                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
659                                                 NA
660                                                 NA
661                                                 NA
662                                                 NA
663                                                 NA

[664 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name  First Name     Last Name         Industry   Title  \
0                      NaN         NaN           NaN              NaN     NaN
1                 Angela P      Angela             P      Photography    Host
2    Kanhnika Khanthavixay    Kanhnika  Khanthavixay       Technology  Member
3                 Friz Ela        Friz           Ela                   Member
4           Pascal Germain      Pascal       Germain       Technology  Member
..                     ...         ...           ...              ...     ...
660            Maros Feher       Maros         Feher                   Member
661        Barrington Edie  Barrington          Edie                   Member
662          Matthew Haupt     Matthew         Haupt  Tax and Finance  Member
663              Rits Ritz        Rits          Ritz       Consulting  Member
664          Aaron Blevins       Aaron       Blevins                   Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
660                                                                     NA
661                                                                     NA
662                                                            Houston, TX
663                                                                     NA
664                                                           Columbus, OH

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
660                                                 NA
661                                                 NA
662  Currently a tax professional, getting out of t...
663                                                 NA
664                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
660                                  NA
661                                  NA
662                                  NA
663                                  NA
664                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
660                                                 NA
661                                                 NA
662                                                 NA
663                                                 NA
664                                                 NA

[665 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name  First Name     Last Name         Industry   Title  \
0                      NaN         NaN           NaN              NaN     NaN
1                 Angela P      Angela             P      Photography    Host
2    Kanhnika Khanthavixay    Kanhnika  Khanthavixay       Technology  Member
3                 Friz Ela        Friz           Ela                   Member
4           Pascal Germain      Pascal       Germain       Technology  Member
..                     ...         ...           ...              ...     ...
661        Barrington Edie  Barrington          Edie                   Member
662          Matthew Haupt     Matthew         Haupt  Tax and Finance  Member
663              Rits Ritz        Rits          Ritz       Consulting  Member
664          Aaron Blevins       Aaron       Blevins                   Member
665                Kevin R       Kevin             R                   Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
661                                                                     NA
662                                                            Houston, TX
663                                                                     NA
664                                                           Columbus, OH
665                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
661                                                 NA
662  Currently a tax professional, getting out of t...
663                                                 NA
664                                                 NA
665                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
661                                  NA
662                                  NA
663                                  NA
664                                  NA
665                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
661                                                 NA
662                                                 NA
663                                                 NA
664                                                 NA
665                                                 NA

[666 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name         Industry   Title  \
0                      NaN        NaN           NaN              NaN     NaN
1                 Angela P     Angela             P      Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay       Technology  Member
3                 Friz Ela       Friz           Ela                   Member
4           Pascal Germain     Pascal       Germain       Technology  Member
..                     ...        ...           ...              ...     ...
662          Matthew Haupt    Matthew         Haupt  Tax and Finance  Member
663              Rits Ritz       Rits          Ritz       Consulting  Member
664          Aaron Blevins      Aaron       Blevins                   Member
665                Kevin R      Kevin             R                   Member
666     Olivier Crisostomo    Olivier    Crisostomo                   Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
662                                                            Houston, TX
663                                                                     NA
664                                                           Columbus, OH
665                                                                     NA
666                                                           Chamblee, GA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
662  Currently a tax professional, getting out of t...
663                                                 NA
664                                                 NA
665                                                 NA
666                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
662                                  NA
663                                  NA
664                                  NA
665                                  NA
666                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
662                                                 NA
663                                                 NA
664                                                 NA
665                                                 NA
666                                                 NA

[667 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
663              Rits Ritz       Rits          Ritz     Consulting  Member
664          Aaron Blevins      Aaron       Blevins                 Member
665                Kevin R      Kevin             R                 Member
666     Olivier Crisostomo    Olivier    Crisostomo                 Member
667            Derek Healy      Derek         Healy  Manufacturing  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
663                                                                     NA
664                                                           Columbus, OH
665                                                                     NA
666                                                           Chamblee, GA
667  Grab me on Linkedin, happy to share my experie...   Sydney, Australia

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
663                                                 NA
664                                                 NA
665                                                 NA
666                                                 NA
667                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
663                                  NA
664                                  NA
665                                  NA
666                                  NA
667                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
663                                                 NA
664                                                 NA
665                                                 NA
666                                                 NA
667      https://www.linkedin.com/in/derek-h-27554171/

[668 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
664          Aaron Blevins      Aaron       Blevins                 Member
665                Kevin R      Kevin             R                 Member
666     Olivier Crisostomo    Olivier    Crisostomo                 Member
667            Derek Healy      Derek         Healy  Manufacturing  Member
668            Juan Acaron       Juan        Acaron                 Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
664                                                              Columbus, OH
665                                                                        NA
666                                                              Chamblee, GA
667  Grab me on Linkedin, happy to share my experie...      Sydney, Australia
668  Combat Medic of the US ARMY. Working on crypto...  San Juan, Puerto Rico

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
664                                                 NA
665                                                 NA
666                                                 NA
667                                                 NA
668  Love to read, develop multi-national connectio...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
664                                  NA
665                                  NA
666                                  NA
667                                  NA
668                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
664                                                 NA
665                                                 NA
666                                                 NA
667      https://www.linkedin.com/in/derek-h-27554171/
668                                                 NA

[669 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
665                Kevin R      Kevin             R                 Member
666     Olivier Crisostomo    Olivier    Crisostomo                 Member
667            Derek Healy      Derek         Healy  Manufacturing  Member
668            Juan Acaron       Juan        Acaron                 Member
669         demitrey karas   demitrey         karas                 Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
665                                                                        NA
666                                                              Chamblee, GA
667  Grab me on Linkedin, happy to share my experie...      Sydney, Australia
668  Combat Medic of the US ARMY. Working on crypto...  San Juan, Puerto Rico
669                                                                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
665                                                 NA
666                                                 NA
667                                                 NA
668  Love to read, develop multi-national connectio...
669                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
665                                  NA
666                                  NA
667                                  NA
668                                  NA
669                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
665                                                 NA
666                                                 NA
667      https://www.linkedin.com/in/derek-h-27554171/
668                                                 NA
669                                                 NA

[670 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
666     Olivier Crisostomo    Olivier    Crisostomo                 Member
667            Derek Healy      Derek         Healy  Manufacturing  Member
668            Juan Acaron       Juan        Acaron                 Member
669         demitrey karas   demitrey         karas                 Member
670               Thomas r     Thomas             r                 Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
666                                                              Chamblee, GA
667  Grab me on Linkedin, happy to share my experie...      Sydney, Australia
668  Combat Medic of the US ARMY. Working on crypto...  San Juan, Puerto Rico
669                                                                        NA
670                                                                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
666                                                 NA
667                                                 NA
668  Love to read, develop multi-national connectio...
669                                                 NA
670                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
666                                  NA
667                                  NA
668                                  NA
669                                  NA
670                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
666                                                 NA
667      https://www.linkedin.com/in/derek-h-27554171/
668                                                 NA
669                                                 NA
670                                                 NA

[671 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
667            Derek Healy      Derek         Healy  Manufacturing  Member
668            Juan Acaron       Juan        Acaron                 Member
669         demitrey karas   demitrey         karas                 Member
670               Thomas r     Thomas             r                 Member
671          Jeremy Sotzen     Jeremy        Sotzen                 Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
667  Grab me on Linkedin, happy to share my experie...      Sydney, Australia
668  Combat Medic of the US ARMY. Working on crypto...  San Juan, Puerto Rico
669                                                                        NA
670                                                                        NA
671                                                                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
667                                                 NA
668  Love to read, develop multi-national connectio...
669                                                 NA
670                                                 NA
671                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
667                                  NA
668                                  NA
669                                  NA
670                                  NA
671                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
667      https://www.linkedin.com/in/derek-h-27554171/
668                                                 NA
669                                                 NA
670                                                 NA
671                                                 NA

[672 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
668            Juan Acaron       Juan        Acaron               Member
669         demitrey karas   demitrey         karas               Member
670               Thomas r     Thomas             r               Member
671          Jeremy Sotzen     Jeremy        Sotzen               Member
672          Steven Barrow     Steven        Barrow               Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
668  Combat Medic of the US ARMY. Working on crypto...  San Juan, Puerto Rico
669                                                                        NA
670                                                                        NA
671                                                                        NA
672                                                                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
668  Love to read, develop multi-national connectio...
669                                                 NA
670                                                 NA
671                                                 NA
672                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
668                                  NA
669                                  NA
670                                  NA
671                                  NA
672                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
668                                                 NA
669                                                 NA
670                                                 NA
671                                                 NA
672                                                 NA

[673 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
669         demitrey karas   demitrey         karas               Member
670               Thomas r     Thomas             r               Member
671          Jeremy Sotzen     Jeremy        Sotzen               Member
672          Steven Barrow     Steven        Barrow               Member
673           GEORGE TISEN     GEORGE         TISEN               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
669                                                                     NA
670                                                                     NA
671                                                                     NA
672                                                                     NA
673                                                          Las Vegas, NV

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
669                                                 NA
670                                                 NA
671                                                 NA
672                                                 NA
673                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
669                                  NA
670                                  NA
671                                  NA
672                                  NA
673                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
669                                                 NA
670                                                 NA
671                                                 NA
672                                                 NA
673                                                 NA

[674 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
670               Thomas r     Thomas             r               Member
671          Jeremy Sotzen     Jeremy        Sotzen               Member
672          Steven Barrow     Steven        Barrow               Member
673           GEORGE TISEN     GEORGE         TISEN               Member
674            Luke CHEUNG       Luke        CHEUNG               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
670
671
672
673
674

                       Location  \
0                           NaN
1                    Marion, TX
2                            NA
3             San Francisco, CA
4            Boisbriand, Canada
..                          ...
670                          NA
671                          NA
672                          NA
673               Las Vegas, NV
674  Hong Kong, Hong Kong-China

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
670                                                 NA
671                                                 NA
672                                                 NA
673                                                 NA
674                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
670                                  NA
671                                  NA
672                                  NA
673                                  NA
674                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
670                                                 NA
671                                                 NA
672                                                 NA
673                                                 NA
674                                                 NA

[675 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
671          Jeremy Sotzen     Jeremy        Sotzen               Member
672          Steven Barrow     Steven        Barrow               Member
673           GEORGE TISEN     GEORGE         TISEN               Member
674            Luke CHEUNG       Luke        CHEUNG               Member
675         Mishael Israel    Mishael        Israel               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
671
672
673
674
675

                       Location  \
0                           NaN
1                    Marion, TX
2                            NA
3             San Francisco, CA
4            Boisbriand, Canada
..                          ...
671                          NA
672                          NA
673               Las Vegas, NV
674  Hong Kong, Hong Kong-China
675                          NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
671                                                 NA
672                                                 NA
673                                                 NA
674                                                 NA
675                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
671                                  NA
672                                  NA
673                                  NA
674                                  NA
675                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
671                                                 NA
672                                                 NA
673                                                 NA
674                                                 NA
675                                                 NA

[676 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name   First Name     Last Name     Industry   Title  \
0                      NaN          NaN           NaN          NaN     NaN
1                 Angela P       Angela             P  Photography    Host
2    Kanhnika Khanthavixay     Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela         Friz           Ela               Member
4           Pascal Germain       Pascal       Germain   Technology  Member
..                     ...          ...           ...          ...     ...
672          Steven Barrow       Steven        Barrow               Member
673           GEORGE TISEN       GEORGE         TISEN               Member
674            Luke CHEUNG         Luke        CHEUNG               Member
675         Mishael Israel      Mishael        Israel               Member
676      Christopher MCCOY  Christopher         MCCOY    Education  Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
672
673
674
675
676

                       Location  \
0                           NaN
1                    Marion, TX
2                            NA
3             San Francisco, CA
4            Boisbriand, Canada
..                          ...
672                          NA
673               Las Vegas, NV
674  Hong Kong, Hong Kong-China
675                          NA
676                          NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
672                                                 NA
673                                                 NA
674                                                 NA
675                                                 NA
676                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
672                                  NA
673                                  NA
674                                  NA
675                                  NA
676                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
672                                                 NA
673                                                 NA
674                                                 NA
675                                                 NA
676                                                 NA

[677 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name   First Name     Last Name     Industry   Title  \
0                      NaN          NaN           NaN          NaN     NaN
1                 Angela P       Angela             P  Photography    Host
2    Kanhnika Khanthavixay     Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela         Friz           Ela               Member
4           Pascal Germain       Pascal       Germain   Technology  Member
..                     ...          ...           ...          ...     ...
673           GEORGE TISEN       GEORGE         TISEN               Member
674            Luke CHEUNG         Luke        CHEUNG               Member
675         Mishael Israel      Mishael        Israel               Member
676      Christopher MCCOY  Christopher         MCCOY    Education  Member
677          Julien Châtel       Julien        Châtel               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
673
674
675
676
677

                       Location  \
0                           NaN
1                    Marion, TX
2                            NA
3             San Francisco, CA
4            Boisbriand, Canada
..                          ...
673               Las Vegas, NV
674  Hong Kong, Hong Kong-China
675                          NA
676                          NA
677                          NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
673                                                 NA
674                                                 NA
675                                                 NA
676                                                 NA
677                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
673                                  NA
674                                  NA
675                                  NA
676                                  NA
677                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
673                                                 NA
674                                                 NA
675                                                 NA
676                                                 NA
677                                                 NA

[678 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name   First Name     Last Name     Industry   Title  \
0                      NaN          NaN           NaN          NaN     NaN
1                 Angela P       Angela             P  Photography    Host
2    Kanhnika Khanthavixay     Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela         Friz           Ela               Member
4           Pascal Germain       Pascal       Germain   Technology  Member
..                     ...          ...           ...          ...     ...
674            Luke CHEUNG         Luke        CHEUNG               Member
675         Mishael Israel      Mishael        Israel               Member
676      Christopher MCCOY  Christopher         MCCOY    Education  Member
677          Julien Châtel       Julien        Châtel               Member
678         Robert Ledbury       Robert       Ledbury               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
674
675
676
677
678

                       Location  \
0                           NaN
1                    Marion, TX
2                            NA
3             San Francisco, CA
4            Boisbriand, Canada
..                          ...
674  Hong Kong, Hong Kong-China
675                          NA
676                          NA
677                          NA
678  Portsmouth, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
674                                                 NA
675                                                 NA
676                                                 NA
677                                                 NA
678  I am Bob, 59 young, living in the UK. I am int...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
674                                  NA
675                                  NA
676                                  NA
677                                  NA
678                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
674                                                 NA
675                                                 NA
676                                                 NA
677                                                 NA
678  https://www.linkedin.com/feed/?trk=onboarding-...

[679 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name   First Name     Last Name      Industry   Title  \
0                      NaN          NaN           NaN           NaN     NaN
1                 Angela P       Angela             P   Photography    Host
2    Kanhnika Khanthavixay     Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela         Friz           Ela                Member
4           Pascal Germain       Pascal       Germain    Technology  Member
..                     ...          ...           ...           ...     ...
675         Mishael Israel      Mishael        Israel                Member
676      Christopher MCCOY  Christopher         MCCOY     Education  Member
677          Julien Châtel       Julien        Châtel                Member
678         Robert Ledbury       Robert       Ledbury                Member
679         Jeremy Premeau       Jeremy       Premeau  Construction  Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
675
676
677
678
679

                       Location  \
0                           NaN
1                    Marion, TX
2                            NA
3             San Francisco, CA
4            Boisbriand, Canada
..                          ...
675                          NA
676                          NA
677                          NA
678  Portsmouth, United Kingdom
679               Waterford, WI

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
675                                                 NA
676                                                 NA
677                                                 NA
678  I am Bob, 59 young, living in the UK. I am int...
679  Own 2 businesses. Just purchased 3rd in August...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
675                                  NA
676                                  NA
677                                  NA
678                                  NA
679                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
675                                                 NA
676                                                 NA
677                                                 NA
678  https://www.linkedin.com/feed/?trk=onboarding-...
679                                                 NA

[680 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name   First Name     Last Name      Industry   Title  \
0                      NaN          NaN           NaN           NaN     NaN
1                 Angela P       Angela             P   Photography    Host
2    Kanhnika Khanthavixay     Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela         Friz           Ela                Member
4           Pascal Germain       Pascal       Germain    Technology  Member
..                     ...          ...           ...           ...     ...
676      Christopher MCCOY  Christopher         MCCOY     Education  Member
677          Julien Châtel       Julien        Châtel                Member
678         Robert Ledbury       Robert       Ledbury                Member
679         Jeremy Premeau       Jeremy       Premeau  Construction  Member
680         joseph hathorn       joseph       hathorn                Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
676
677
678
679
680

                       Location  \
0                           NaN
1                    Marion, TX
2                            NA
3             San Francisco, CA
4            Boisbriand, Canada
..                          ...
676                          NA
677                          NA
678  Portsmouth, United Kingdom
679               Waterford, WI
680                          NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
676                                                 NA
677                                                 NA
678  I am Bob, 59 young, living in the UK. I am int...
679  Own 2 businesses. Just purchased 3rd in August...
680                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
676                                  NA
677                                  NA
678                                  NA
679                                  NA
680                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
676                                                 NA
677                                                 NA
678  https://www.linkedin.com/feed/?trk=onboarding-...
679                                                 NA
680                                                 NA

[681 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
677          Julien Châtel     Julien        Châtel                Member
678         Robert Ledbury     Robert       Ledbury                Member
679         Jeremy Premeau     Jeremy       Premeau  Construction  Member
680         joseph hathorn     joseph       hathorn                Member
681             Fred Evans       Fred         Evans                Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
677
678
679
680
681

                       Location  \
0                           NaN
1                    Marion, TX
2                            NA
3             San Francisco, CA
4            Boisbriand, Canada
..                          ...
677                          NA
678  Portsmouth, United Kingdom
679               Waterford, WI
680                          NA
681                          NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
677                                                 NA
678  I am Bob, 59 young, living in the UK. I am int...
679  Own 2 businesses. Just purchased 3rd in August...
680                                                 NA
681                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
677                                  NA
678                                  NA
679                                  NA
680                                  NA
681                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
677                                                 NA
678  https://www.linkedin.com/feed/?trk=onboarding-...
679                                                 NA
680                                                 NA
681                                                 NA

[682 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
678         Robert Ledbury     Robert       Ledbury                Member
679         Jeremy Premeau     Jeremy       Premeau  Construction  Member
680         joseph hathorn     joseph       hathorn                Member
681             Fred Evans       Fred         Evans                Member
682              Tyson Woo      Tyson           Woo                Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
678
679
680
681
682

                       Location  \
0                           NaN
1                    Marion, TX
2                            NA
3             San Francisco, CA
4            Boisbriand, Canada
..                          ...
678  Portsmouth, United Kingdom
679               Waterford, WI
680                          NA
681                          NA
682                          NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
678  I am Bob, 59 young, living in the UK. I am int...
679  Own 2 businesses. Just purchased 3rd in August...
680                                                 NA
681                                                 NA
682                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
678                                  NA
679                                  NA
680                                  NA
681                                  NA
682                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
678  https://www.linkedin.com/feed/?trk=onboarding-...
679                                                 NA
680                                                 NA
681                                                 NA
682                                                 NA

[683 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
679         Jeremy Premeau     Jeremy       Premeau  Construction  Member
680         joseph hathorn     joseph       hathorn                Member
681             Fred Evans       Fred         Evans                Member
682              Tyson Woo      Tyson           Woo                Member
683             Kai Ringli        Kai        Ringli                Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
679                                                          Waterford, WI
680                                                                     NA
681                                                                     NA
682                                                                     NA
683                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
679  Own 2 businesses. Just purchased 3rd in August...
680                                                 NA
681                                                 NA
682                                                 NA
683                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
679                                  NA
680                                  NA
681                                  NA
682                                  NA
683                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
679                                                 NA
680                                                 NA
681                                                 NA
682                                                 NA
683                                                 NA

[684 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
680         joseph hathorn     joseph       hathorn               Member
681             Fred Evans       Fred         Evans               Member
682              Tyson Woo      Tyson           Woo               Member
683             Kai Ringli        Kai        Ringli               Member
684          Michelle Wang   Michelle          Wang               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
680                                                                     NA
681                                                                     NA
682                                                                     NA
683                                                                     NA
684                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
680                                                 NA
681                                                 NA
682                                                 NA
683                                                 NA
684                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
680                                  NA
681                                  NA
682                                  NA
683                                  NA
684                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
680                                                 NA
681                                                 NA
682                                                 NA
683                                                 NA
684                                                 NA

[685 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
681             Fred Evans       Fred         Evans               Member
682              Tyson Woo      Tyson           Woo               Member
683             Kai Ringli        Kai        Ringli               Member
684          Michelle Wang   Michelle          Wang               Member
685         Charles Newton    Charles        Newton               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
681                                                                     NA
682                                                                     NA
683                                                                     NA
684                                                                     NA
685                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
681                                                 NA
682                                                 NA
683                                                 NA
684                                                 NA
685                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
681                                  NA
682                                  NA
683                                  NA
684                                  NA
685                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
681                                                 NA
682                                                 NA
683                                                 NA
684                                                 NA
685                                                 NA

[686 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
682              Tyson Woo      Tyson           Woo               Member
683             Kai Ringli        Kai        Ringli               Member
684          Michelle Wang   Michelle          Wang               Member
685         Charles Newton    Charles        Newton               Member
686           Ryan Dickson       Ryan       Dickson               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
682                                                                     NA
683                                                                     NA
684                                                                     NA
685                                                                     NA
686                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
682                                                 NA
683                                                 NA
684                                                 NA
685                                                 NA
686  Hello, excited to start our Acquisitions busin...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
682                                  NA
683                                  NA
684                                  NA
685                                  NA
686                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
682                                                 NA
683                                                 NA
684                                                 NA
685                                                 NA
686                                                 NA

[687 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
683             Kai Ringli        Kai        Ringli               Member
684          Michelle Wang   Michelle          Wang               Member
685         Charles Newton    Charles        Newton               Member
686           Ryan Dickson       Ryan       Dickson               Member
687              Georges H    Georges             H               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
683                                                                     NA
684                                                                     NA
685                                                                     NA
686                                                                     NA
687                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
683                                                 NA
684                                                 NA
685                                                 NA
686  Hello, excited to start our Acquisitions busin...
687                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
683                                  NA
684                                  NA
685                                  NA
686                                  NA
687                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
683                                                 NA
684                                                 NA
685                                                 NA
686                                                 NA
687                                                 NA

[688 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
684          Michelle Wang   Michelle          Wang               Member
685         Charles Newton    Charles        Newton               Member
686           Ryan Dickson       Ryan       Dickson               Member
687              Georges H    Georges             H               Member
688        Curtis Sambrook     Curtis      Sambrook               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
684                                                                     NA
685                                                                     NA
686                                                                     NA
687                                                                     NA
688                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
684                                                 NA
685                                                 NA
686  Hello, excited to start our Acquisitions busin...
687                                                 NA
688                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
684                                  NA
685                                  NA
686                                  NA
687                                  NA
688                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
684                                                 NA
685                                                 NA
686                                                 NA
687                                                 NA
688                                                 NA

[689 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
685         Charles Newton    Charles        Newton                 Member
686           Ryan Dickson       Ryan       Dickson                 Member
687              Georges H    Georges             H                 Member
688        Curtis Sambrook     Curtis      Sambrook                 Member
689          Rakesh Hallan     Rakesh        Hallan  Manufacturing  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
685                                                                     NA
686                                                                     NA
687                                                                     NA
688                                                                     NA
689                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
685                                                 NA
686  Hello, excited to start our Acquisitions busin...
687                                                 NA
688                                                 NA
689                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
685                                  NA
686                                  NA
687                                  NA
688                                  NA
689                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
685                                                 NA
686                                                 NA
687                                                 NA
688                                                 NA
689                                                 NA

[690 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                       Full name First Name     Last Name       Industry  \
0                            NaN        NaN           NaN            NaN
1                       Angela P     Angela             P    Photography
2          Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology
3                       Friz Ela       Friz           Ela
4                 Pascal Germain     Pascal       Germain     Technology
..                           ...        ...           ...            ...
686                 Ryan Dickson       Ryan       Dickson
687                    Georges H    Georges             H
688              Curtis Sambrook     Curtis      Sambrook
689                Rakesh Hallan     Rakesh        Hallan  Manufacturing
690  Robert & Shirmilla Bagoczky     Robert      Bagoczky

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
686  Member
687  Member
688  Member
689  Member
690  Member

               Location                                              Intro  \
0                   NaN                                                NaN
1            Marion, TX  Hi Everyone I had a business that l started fr...
2                    NA                                                 NA
3     San Francisco, CA                                                 NA
4    Boisbriand, Canada  Investor + Business Aquisition + Business Opti...
..                  ...                                                ...
686                  NA  Hello, excited to start our Acquisitions busin...
687                  NA                                                 NA
688                  NA                                                 NA
689                  NA                                                 NA
690                  NA                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
686                                  NA
687                                  NA
688                                  NA
689                                  NA
690                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
686                                                 NA
687                                                 NA
688                                                 NA
689                                                 NA
690                                                 NA

[691 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                       Full name First Name     Last Name       Industry  \
0                            NaN        NaN           NaN            NaN
1                       Angela P     Angela             P    Photography
2          Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology
3                       Friz Ela       Friz           Ela
4                 Pascal Germain     Pascal       Germain     Technology
..                           ...        ...           ...            ...
687                    Georges H    Georges             H
688              Curtis Sambrook     Curtis      Sambrook
689                Rakesh Hallan     Rakesh        Hallan  Manufacturing
690  Robert & Shirmilla Bagoczky     Robert      Bagoczky
691                Chris Dougall      Chris       Dougall

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
687  Member
688  Member
689  Member
690  Member
691  Member

                Location                                              Intro  \
0                    NaN                                                NaN
1             Marion, TX  Hi Everyone I had a business that l started fr...
2                     NA                                                 NA
3      San Francisco, CA                                                 NA
4     Boisbriand, Canada  Investor + Business Aquisition + Business Opti...
..                   ...                                                ...
687                   NA                                                 NA
688                   NA                                                 NA
689                   NA                                                 NA
690                   NA                                                 NA
691  Adelaide, Australia                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
687                                  NA
688                                  NA
689                                  NA
690                                  NA
691                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
687                                                 NA
688                                                 NA
689                                                 NA
690                                                 NA
691          https://www.linkedin.com/in/chrisdougall/

[692 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                       Full name First Name     Last Name       Industry  \
0                            NaN        NaN           NaN            NaN
1                       Angela P     Angela             P    Photography
2          Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology
3                       Friz Ela       Friz           Ela
4                 Pascal Germain     Pascal       Germain     Technology
..                           ...        ...           ...            ...
688              Curtis Sambrook     Curtis      Sambrook
689                Rakesh Hallan     Rakesh        Hallan  Manufacturing
690  Robert & Shirmilla Bagoczky     Robert      Bagoczky
691                Chris Dougall      Chris       Dougall
692                 Cina Ghiassi       Cina       Ghiassi

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
688  Member
689  Member
690  Member
691  Member
692  Member

                Location                                              Intro  \
0                    NaN                                                NaN
1             Marion, TX  Hi Everyone I had a business that l started fr...
2                     NA                                                 NA
3      San Francisco, CA                                                 NA
4     Boisbriand, Canada  Investor + Business Aquisition + Business Opti...
..                   ...                                                ...
688                   NA                                                 NA
689                   NA                                                 NA
690                   NA                                                 NA
691  Adelaide, Australia                                                 NA
692     Perth, Australia                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
688                                  NA
689                                  NA
690                                  NA
691                                  NA
692                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
688                                                 NA
689                                                 NA
690                                                 NA
691          https://www.linkedin.com/in/chrisdougall/
692                                                 NA

[693 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                       Full name First Name     Last Name       Industry  \
0                            NaN        NaN           NaN            NaN
1                       Angela P     Angela             P    Photography
2          Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology
3                       Friz Ela       Friz           Ela
4                 Pascal Germain     Pascal       Germain     Technology
..                           ...        ...           ...            ...
689                Rakesh Hallan     Rakesh        Hallan  Manufacturing
690  Robert & Shirmilla Bagoczky     Robert      Bagoczky
691                Chris Dougall      Chris       Dougall
692                 Cina Ghiassi       Cina       Ghiassi
693                      Falco N      Falco             N

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
689  Member
690  Member
691  Member
692  Member
693  Member

                Location                                              Intro  \
0                    NaN                                                NaN
1             Marion, TX  Hi Everyone I had a business that l started fr...
2                     NA                                                 NA
3      San Francisco, CA                                                 NA
4     Boisbriand, Canada  Investor + Business Aquisition + Business Opti...
..                   ...                                                ...
689                   NA                                                 NA
690                   NA                                                 NA
691  Adelaide, Australia                                                 NA
692     Perth, Australia                                                 NA
693      Rijeka, Croatia                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
689                                  NA
690                                  NA
691                                  NA
692                                  NA
693                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
689                                                 NA
690                                                 NA
691          https://www.linkedin.com/in/chrisdougall/
692                                                 NA
693                                                 NA

[694 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                       Full name First Name     Last Name     Industry  \
0                            NaN        NaN           NaN          NaN
1                       Angela P     Angela             P  Photography
2          Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology
3                       Friz Ela       Friz           Ela
4                 Pascal Germain     Pascal       Germain   Technology
..                           ...        ...           ...          ...
690  Robert & Shirmilla Bagoczky     Robert      Bagoczky
691                Chris Dougall      Chris       Dougall
692                 Cina Ghiassi       Cina       Ghiassi
693                      Falco N      Falco             N
694                   Alaric Ong     Alaric           Ong

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
690  Member
691  Member
692  Member
693  Member
694  Member

                 Location                                              Intro  \
0                     NaN                                                NaN
1              Marion, TX  Hi Everyone I had a business that l started fr...
2                      NA                                                 NA
3       San Francisco, CA                                                 NA
4      Boisbriand, Canada  Investor + Business Aquisition + Business Opti...
..                    ...                                                ...
690                    NA                                                 NA
691   Adelaide, Australia                                                 NA
692      Perth, Australia                                                 NA
693       Rijeka, Croatia                                                 NA
694  Singapore, Singapore                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
690                                  NA
691                                  NA
692                                  NA
693                                  NA
694                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
690                                                 NA
691          https://www.linkedin.com/in/chrisdougall/
692                                                 NA
693                                                 NA
694                                                 NA

[695 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
691          Chris Dougall      Chris       Dougall               Member
692           Cina Ghiassi       Cina       Ghiassi               Member
693                Falco N      Falco             N               Member
694             Alaric Ong     Alaric           Ong               Member
695           Alexis Wilke     Alexis         Wilke               Member

                                                 About              Location  \
0                                                  NaN                   NaN
1    l'm Angela and here to help you succeed. l am ...            Marion, TX
2    I have over 15+ years in project management. I...                    NA
3        I'm part of the team here at Acquisitions.com     San Francisco, CA
4    25+ years of expertise as business owner Most ...    Boisbriand, Canada
..                                                 ...                   ...
691                                                      Adelaide, Australia
692                                                         Perth, Australia
693                                                          Rijeka, Croatia
694                                                     Singapore, Singapore
695                                                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
691                                                 NA
692                                                 NA
693                                                 NA
694                                                 NA
695                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
691                                  NA
692                                  NA
693                                  NA
694                                  NA
695                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
691          https://www.linkedin.com/in/chrisdougall/
692                                                 NA
693                                                 NA
694                                                 NA
695                                                 NA

[696 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
692           Cina Ghiassi       Cina       Ghiassi               Member
693                Falco N      Falco             N               Member
694             Alaric Ong     Alaric           Ong               Member
695           Alexis Wilke     Alexis         Wilke               Member
696               Rajesh Y     Rajesh             Y               Member

                                                 About              Location  \
0                                                  NaN                   NaN
1    l'm Angela and here to help you succeed. l am ...            Marion, TX
2    I have over 15+ years in project management. I...                    NA
3        I'm part of the team here at Acquisitions.com     San Francisco, CA
4    25+ years of expertise as business owner Most ...    Boisbriand, Canada
..                                                 ...                   ...
692                                                         Perth, Australia
693                                                          Rijeka, Croatia
694                                                     Singapore, Singapore
695                                                                       NA
696                                                              Chicago, IL

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
692                                                 NA
693                                                 NA
694                                                 NA
695                                                 NA
696                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
692                                  NA
693                                  NA
694                                  NA
695                                  NA
696                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
692                                                 NA
693                                                 NA
694                                                 NA
695                                                 NA
696                                                 NA

[697 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
693                Falco N      Falco             N               Member
694             Alaric Ong     Alaric           Ong               Member
695           Alexis Wilke     Alexis         Wilke               Member
696               Rajesh Y     Rajesh             Y               Member
697       Zachary Crawford    Zachary      Crawford   Technology  Member

                                                 About              Location  \
0                                                  NaN                   NaN
1    l'm Angela and here to help you succeed. l am ...            Marion, TX
2    I have over 15+ years in project management. I...                    NA
3        I'm part of the team here at Acquisitions.com     San Francisco, CA
4    25+ years of expertise as business owner Most ...    Boisbriand, Canada
..                                                 ...                   ...
693                                                          Rijeka, Croatia
694                                                     Singapore, Singapore
695                                                                       NA
696                                                              Chicago, IL
697                                                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
693                                                 NA
694                                                 NA
695                                                 NA
696                                                 NA
697  Passionate about helping others, learning new ...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
693                                  NA
694                                  NA
695                                  NA
696                                  NA
697                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
693                                                 NA
694                                                 NA
695                                                 NA
696                                                 NA
697                                                 NA

[698 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
694             Alaric Ong     Alaric           Ong               Member
695           Alexis Wilke     Alexis         Wilke               Member
696               Rajesh Y     Rajesh             Y               Member
697       Zachary Crawford    Zachary      Crawford   Technology  Member
698              Jose Ayon       Jose          Ayon               Member

                                                 About              Location  \
0                                                  NaN                   NaN
1    l'm Angela and here to help you succeed. l am ...            Marion, TX
2    I have over 15+ years in project management. I...                    NA
3        I'm part of the team here at Acquisitions.com     San Francisco, CA
4    25+ years of expertise as business owner Most ...    Boisbriand, Canada
..                                                 ...                   ...
694                                                     Singapore, Singapore
695                                                                       NA
696                                                              Chicago, IL
697                                                                       NA
698                                                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
694                                                 NA
695                                                 NA
696                                                 NA
697  Passionate about helping others, learning new ...
698                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
694                                  NA
695                                  NA
696                                  NA
697                                  NA
698                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
694                                                 NA
695                                                 NA
696                                                 NA
697                                                 NA
698                                                 NA

[699 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
695           Alexis Wilke     Alexis         Wilke               Member
696               Rajesh Y     Rajesh             Y               Member
697       Zachary Crawford    Zachary      Crawford   Technology  Member
698              Jose Ayon       Jose          Ayon               Member
699                  R&M P        R&M             P               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
695                                                                     NA
696                                                            Chicago, IL
697                                                                     NA
698                                                                     NA
699                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
695                                                 NA
696                                                 NA
697  Passionate about helping others, learning new ...
698                                                 NA
699                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
695                                  NA
696                                  NA
697                                  NA
698                                  NA
699                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
695                                                 NA
696                                                 NA
697                                                 NA
698                                                 NA
699                                                 NA

[700 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
696               Rajesh Y     Rajesh             Y               Member
697       Zachary Crawford    Zachary      Crawford   Technology  Member
698              Jose Ayon       Jose          Ayon               Member
699                  R&M P        R&M             P               Member
700      William Humphreys    William     Humphreys               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
696
697
698
699
700

                   Location  \
0                       NaN
1                Marion, TX
2                        NA
3         San Francisco, CA
4        Boisbriand, Canada
..                      ...
696             Chicago, IL
697                      NA
698                      NA
699                      NA
700  Oxford, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
696                                                 NA
697  Passionate about helping others, learning new ...
698                                                 NA
699                                                 NA
700                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
696                                  NA
697                                  NA
698                                  NA
699                                  NA
700                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
696                                                 NA
697                                                 NA
698                                                 NA
699                                                 NA
700                                                 NA

[701 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
697       Zachary Crawford    Zachary      Crawford   Technology  Member
698              Jose Ayon       Jose          Ayon               Member
699                  R&M P        R&M             P               Member
700      William Humphreys    William     Humphreys               Member
701            Kelton Fung     Kelton          Fung               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
697
698
699
700
701

                   Location  \
0                       NaN
1                Marion, TX
2                        NA
3         San Francisco, CA
4        Boisbriand, Canada
..                      ...
697                      NA
698                      NA
699                      NA
700  Oxford, United Kingdom
701   Richmond Hill, Canada

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
697  Passionate about helping others, learning new ...
698                                                 NA
699                                                 NA
700                                                 NA
701                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
697                                  NA
698                                  NA
699                                  NA
700                                  NA
701                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
697                                                 NA
698                                                 NA
699                                                 NA
700                                                 NA
701                                                 NA

[702 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
698              Jose Ayon       Jose          Ayon               Member
699                  R&M P        R&M             P               Member
700      William Humphreys    William     Humphreys               Member
701            Kelton Fung     Kelton          Fung               Member
702            James Sackl      James         Sackl               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
698
699
700
701
702

                   Location  \
0                       NaN
1                Marion, TX
2                        NA
3         San Francisco, CA
4        Boisbriand, Canada
..                      ...
698                      NA
699                      NA
700  Oxford, United Kingdom
701   Richmond Hill, Canada
702       Sydney, Australia

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
698                                                 NA
699                                                 NA
700                                                 NA
701                                                 NA
702                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
698                                  NA
699                                  NA
700                                  NA
701                                  NA
702                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
698                                                 NA
699                                                 NA
700                                                 NA
701                                                 NA
702                                                 NA

[703 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
699                  R&M P        R&M             P               Member
700      William Humphreys    William     Humphreys               Member
701            Kelton Fung     Kelton          Fung               Member
702            James Sackl      James         Sackl               Member
703               Joe Long        Joe          Long               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
699
700
701
702
703

                   Location  \
0                       NaN
1                Marion, TX
2                        NA
3         San Francisco, CA
4        Boisbriand, Canada
..                      ...
699                      NA
700  Oxford, United Kingdom
701   Richmond Hill, Canada
702       Sydney, Australia
703                      NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
699                                                 NA
700                                                 NA
701                                                 NA
702                                                 NA
703                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
699                                  NA
700                                  NA
701                                  NA
702                                  NA
703                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
699                                                 NA
700                                                 NA
701                                                 NA
702                                                 NA
703                                                 NA

[704 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
700      William Humphreys    William     Humphreys               Member
701            Kelton Fung     Kelton          Fung               Member
702            James Sackl      James         Sackl               Member
703               Joe Long        Joe          Long               Member
704                    J O          J             O               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
700
701
702
703
704

                   Location  \
0                       NaN
1                Marion, TX
2                        NA
3         San Francisco, CA
4        Boisbriand, Canada
..                      ...
700  Oxford, United Kingdom
701   Richmond Hill, Canada
702       Sydney, Australia
703                      NA
704                      NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
700                                                 NA
701                                                 NA
702                                                 NA
703                                                 NA
704                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
700                                  NA
701                                  NA
702                                  NA
703                                  NA
704                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
700                                                 NA
701                                                 NA
702                                                 NA
703                                                 NA
704                                                 NA

[705 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
701            Kelton Fung     Kelton          Fung               Member
702            James Sackl      James         Sackl               Member
703               Joe Long        Joe          Long               Member
704                    J O          J             O               Member
705             Rick Yates       Rick         Yates   Technology  Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
701                                                     Richmond Hill, Canada
702                                                         Sydney, Australia
703                                                                        NA
704                                                                        NA
705                                                                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
701                                                 NA
702                                                 NA
703                                                 NA
704                                                 NA
705  I’m a UK based entrepreneur with a particular ...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
701                                  NA
702                                  NA
703                                  NA
704                                  NA
705                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
701                                                 NA
702                                                 NA
703                                                 NA
704                                                 NA
705                                                 NA

[706 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name               Industry  \
0                      NaN        NaN           NaN                    NaN
1                 Angela P     Angela             P            Photography
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay             Technology
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain             Technology
..                     ...        ...           ...                    ...
702            James Sackl      James         Sackl
703               Joe Long        Joe          Long
704                    J O          J             O
705             Rick Yates       Rick         Yates             Technology
706             Don McCall        Don        McCall  Business Optimization

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
702  Member
703  Member
704  Member
705  Member
706  Member

               Location                                              Intro  \
0                   NaN                                                NaN
1            Marion, TX  Hi Everyone I had a business that l started fr...
2                    NA                                                 NA
3     San Francisco, CA                                                 NA
4    Boisbriand, Canada  Investor + Business Aquisition + Business Opti...
..                  ...                                                ...
702   Sydney, Australia                                                 NA
703                  NA                                                 NA
704                  NA                                                 NA
705                  NA  I’m a UK based entrepreneur with a particular ...
706     Calgary, Canada                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
702                                  NA
703                                  NA
704                                  NA
705                                  NA
706                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
702                                                 NA
703                                                 NA
704                                                 NA
705                                                 NA
706                                                 NA

[707 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name               Industry  \
0                      NaN        NaN           NaN                    NaN
1                 Angela P     Angela             P            Photography
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay             Technology
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain             Technology
..                     ...        ...           ...                    ...
703               Joe Long        Joe          Long
704                    J O          J             O
705             Rick Yates       Rick         Yates             Technology
706             Don McCall        Don        McCall  Business Optimization
707         Wali Aziz-Wali       Wali     Aziz-Wali

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
703  Member
704  Member
705  Member
706  Member
707  Member

               Location                                              Intro  \
0                   NaN                                                NaN
1            Marion, TX  Hi Everyone I had a business that l started fr...
2                    NA                                                 NA
3     San Francisco, CA                                                 NA
4    Boisbriand, Canada  Investor + Business Aquisition + Business Opti...
..                  ...                                                ...
703                  NA                                                 NA
704                  NA                                                 NA
705                  NA  I’m a UK based entrepreneur with a particular ...
706     Calgary, Canada                                                 NA
707                  NA                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
703                                  NA
704                                  NA
705                                  NA
706                                  NA
707                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
703                                                 NA
704                                                 NA
705                                                 NA
706                                                 NA
707                                                 NA

[708 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name  \
0                      NaN        NaN           NaN
1                 Angela P     Angela             P
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain
..                     ...        ...           ...
704                    J O          J             O
705             Rick Yates       Rick         Yates
706             Don McCall        Don        McCall
707         Wali Aziz-Wali       Wali     Aziz-Wali
708        Robert McDonald     Robert      McDonald

                         Industry   Title  \
0                             NaN     NaN
1                     Photography    Host
2                      Technology  Member
3                                  Member
4                      Technology  Member
..                            ...     ...
704                                Member
705                    Technology  Member
706         Business Optimization  Member
707                                Member
708  Skilled Trades, Construction  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
704                                                                     NA
705                                                                     NA
706                                                        Calgary, Canada
707                                                                     NA
708  Hello Acquisition Community - I'm happy to be ...   Kitchener, Canada

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
704                                                 NA
705  I’m a UK based entrepreneur with a particular ...
706                                                 NA
707                                                 NA
708  I have 23 years in manufacturing industry, 10 ...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
704                                  NA
705                                  NA
706                                  NA
707                                  NA
708                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
704                                                 NA
705                                                 NA
706                                                 NA
707                                                 NA
708  https://www.linkedin.com/in/robert-mcdonald-70...

[709 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name  \
0                      NaN        NaN           NaN
1                 Angela P     Angela             P
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain
..                     ...        ...           ...
705             Rick Yates       Rick         Yates
706             Don McCall        Don        McCall
707         Wali Aziz-Wali       Wali     Aziz-Wali
708        Robert McDonald     Robert      McDonald
709          JOHN CHEATHAM       JOHN      CHEATHAM

                         Industry   Title  \
0                             NaN     NaN
1                     Photography    Host
2                      Technology  Member
3                                  Member
4                      Technology  Member
..                            ...     ...
705                    Technology  Member
706         Business Optimization  Member
707                                Member
708  Skilled Trades, Construction  Member
709                                Member

                                                 About             Location  \
0                                                  NaN                  NaN
1    l'm Angela and here to help you succeed. l am ...           Marion, TX
2    I have over 15+ years in project management. I...                   NA
3        I'm part of the team here at Acquisitions.com    San Francisco, CA
4    25+ years of expertise as business owner Most ...   Boisbriand, Canada
..                                                 ...                  ...
705                                                                      NA
706                                                         Calgary, Canada
707                                                                      NA
708  Hello Acquisition Community - I'm happy to be ...    Kitchener, Canada
709                                                     Kuwait City, Kuwait

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
705  I’m a UK based entrepreneur with a particular ...
706                                                 NA
707                                                 NA
708  I have 23 years in manufacturing industry, 10 ...
709  I am an operations research systems analyst fo...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
705                                  NA
706                                  NA
707                                  NA
708                                  NA
709                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
705                                                 NA
706                                                 NA
707                                                 NA
708  https://www.linkedin.com/in/robert-mcdonald-70...
709                                                 NA

[710 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name  \
0                      NaN        NaN           NaN
1                 Angela P     Angela             P
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain
..                     ...        ...           ...
706             Don McCall        Don        McCall
707         Wali Aziz-Wali       Wali     Aziz-Wali
708        Robert McDonald     Robert      McDonald
709          JOHN CHEATHAM       JOHN      CHEATHAM
710         Simon Thompson      Simon      Thompson

                         Industry   Title  \
0                             NaN     NaN
1                     Photography    Host
2                      Technology  Member
3                                  Member
4                      Technology  Member
..                            ...     ...
706         Business Optimization  Member
707                                Member
708  Skilled Trades, Construction  Member
709                                Member
710                  Construction  Member

                                                 About             Location  \
0                                                  NaN                  NaN
1    l'm Angela and here to help you succeed. l am ...           Marion, TX
2    I have over 15+ years in project management. I...                   NA
3        I'm part of the team here at Acquisitions.com    San Francisco, CA
4    25+ years of expertise as business owner Most ...   Boisbriand, Canada
..                                                 ...                  ...
706                                                         Calgary, Canada
707                                                                      NA
708  Hello Acquisition Community - I'm happy to be ...    Kitchener, Canada
709                                                     Kuwait City, Kuwait
710  Hi everyone! My name is Simon. I'm a serial en...                   NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
706                                                 NA
707                                                 NA
708  I have 23 years in manufacturing industry, 10 ...
709  I am an operations research systems analyst fo...
710  Serial entrepreneur with more than 15 years of...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
706                                  NA
707                                  NA
708                                  NA
709                                  NA
710   https://leftcoastperformance.com/

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
706                                                 NA
707                                                 NA
708  https://www.linkedin.com/in/robert-mcdonald-70...
709                                                 NA
710                                                 NA

[711 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name  \
0                      NaN        NaN           NaN
1                 Angela P     Angela             P
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain
..                     ...        ...           ...
707         Wali Aziz-Wali       Wali     Aziz-Wali
708        Robert McDonald     Robert      McDonald
709          JOHN CHEATHAM       JOHN      CHEATHAM
710         Simon Thompson      Simon      Thompson
711          Chris Sutliff      Chris       Sutliff

                          Industry   Title  \
0                              NaN     NaN
1                      Photography    Host
2                       Technology  Member
3                                   Member
4                       Technology  Member
..                             ...     ...
707                                 Member
708   Skilled Trades, Construction  Member
709                                 Member
710                   Construction  Member
711  Electrical Mechanical Service  Member

                                                 About             Location  \
0                                                  NaN                  NaN
1    l'm Angela and here to help you succeed. l am ...           Marion, TX
2    I have over 15+ years in project management. I...                   NA
3        I'm part of the team here at Acquisitions.com    San Francisco, CA
4    25+ years of expertise as business owner Most ...   Boisbriand, Canada
..                                                 ...                  ...
707                                                                      NA
708  Hello Acquisition Community - I'm happy to be ...    Kitchener, Canada
709                                                     Kuwait City, Kuwait
710  Hi everyone! My name is Simon. I'm a serial en...                   NA
711                                                          Hulmeville, PA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
707                                                 NA
708  I have 23 years in manufacturing industry, 10 ...
709  I am an operations research systems analyst fo...
710  Serial entrepreneur with more than 15 years of...
711                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
707                                  NA
708                                  NA
709                                  NA
710   https://leftcoastperformance.com/
711                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
707                                                 NA
708  https://www.linkedin.com/in/robert-mcdonald-70...
709                                                 NA
710                                                 NA
711                                                 NA

[712 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name  \
0                      NaN        NaN           NaN
1                 Angela P     Angela             P
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain
..                     ...        ...           ...
708        Robert McDonald     Robert      McDonald
709          JOHN CHEATHAM       JOHN      CHEATHAM
710         Simon Thompson      Simon      Thompson
711          Chris Sutliff      Chris       Sutliff
712         Marvin Salazar     Marvin       Salazar

                          Industry   Title  \
0                              NaN     NaN
1                      Photography    Host
2                       Technology  Member
3                                   Member
4                       Technology  Member
..                             ...     ...
708   Skilled Trades, Construction  Member
709                                 Member
710                   Construction  Member
711  Electrical Mechanical Service  Member
712                                 Member

                                                 About             Location  \
0                                                  NaN                  NaN
1    l'm Angela and here to help you succeed. l am ...           Marion, TX
2    I have over 15+ years in project management. I...                   NA
3        I'm part of the team here at Acquisitions.com    San Francisco, CA
4    25+ years of expertise as business owner Most ...   Boisbriand, Canada
..                                                 ...                  ...
708  Hello Acquisition Community - I'm happy to be ...    Kitchener, Canada
709                                                     Kuwait City, Kuwait
710  Hi everyone! My name is Simon. I'm a serial en...                   NA
711                                                          Hulmeville, PA
712                                                                      NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
708  I have 23 years in manufacturing industry, 10 ...
709  I am an operations research systems analyst fo...
710  Serial entrepreneur with more than 15 years of...
711                                                 NA
712                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
708                                  NA
709                                  NA
710   https://leftcoastperformance.com/
711                                  NA
712                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
708  https://www.linkedin.com/in/robert-mcdonald-70...
709                                                 NA
710                                                 NA
711                                                 NA
712                                                 NA

[713 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name  \
0                      NaN        NaN           NaN
1                 Angela P     Angela             P
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain
..                     ...        ...           ...
709          JOHN CHEATHAM       JOHN      CHEATHAM
710         Simon Thompson      Simon      Thompson
711          Chris Sutliff      Chris       Sutliff
712         Marvin Salazar     Marvin       Salazar
713         Ariel Sokoloff      Ariel      Sokoloff

                          Industry   Title  \
0                              NaN     NaN
1                      Photography    Host
2                       Technology  Member
3                                   Member
4                       Technology  Member
..                             ...     ...
709                                 Member
710                   Construction  Member
711  Electrical Mechanical Service  Member
712                                 Member
713                                 Member

                                                 About             Location  \
0                                                  NaN                  NaN
1    l'm Angela and here to help you succeed. l am ...           Marion, TX
2    I have over 15+ years in project management. I...                   NA
3        I'm part of the team here at Acquisitions.com    San Francisco, CA
4    25+ years of expertise as business owner Most ...   Boisbriand, Canada
..                                                 ...                  ...
709                                                     Kuwait City, Kuwait
710  Hi everyone! My name is Simon. I'm a serial en...                   NA
711                                                          Hulmeville, PA
712                                                                      NA
713                                                           Baltimore, MD

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
709  I am an operations research systems analyst fo...
710  Serial entrepreneur with more than 15 years of...
711                                                 NA
712                                                 NA
713                                        Aquaculture

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
709                                  NA
710   https://leftcoastperformance.com/
711                                  NA
712                                  NA
713                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
709                                                 NA
710                                                 NA
711                                                 NA
712                                                 NA
713                                                 NA

[714 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name  \
0                      NaN        NaN           NaN
1                 Angela P     Angela             P
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain
..                     ...        ...           ...
710         Simon Thompson      Simon      Thompson
711          Chris Sutliff      Chris       Sutliff
712         Marvin Salazar     Marvin       Salazar
713         Ariel Sokoloff      Ariel      Sokoloff
714           Robert Dicks     Robert         Dicks

                          Industry   Title  \
0                              NaN     NaN
1                      Photography    Host
2                       Technology  Member
3                                   Member
4                       Technology  Member
..                             ...     ...
710                   Construction  Member
711  Electrical Mechanical Service  Member
712                                 Member
713                                 Member
714                                 Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
710  Hi everyone! My name is Simon. I'm a serial en...                  NA
711                                                         Hulmeville, PA
712                                                                     NA
713                                                          Baltimore, MD
714                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
710  Serial entrepreneur with more than 15 years of...
711                                                 NA
712                                                 NA
713                                        Aquaculture
714                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
710   https://leftcoastperformance.com/
711                                  NA
712                                  NA
713                                  NA
714                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
710                                                 NA
711                                                 NA
712                                                 NA
713                                                 NA
714                                                 NA

[715 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name  \
0                      NaN        NaN           NaN
1                 Angela P     Angela             P
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain
..                     ...        ...           ...
711          Chris Sutliff      Chris       Sutliff
712         Marvin Salazar     Marvin       Salazar
713         Ariel Sokoloff      Ariel      Sokoloff
714           Robert Dicks     Robert         Dicks
715         Winston Carter    Winston        Carter

                          Industry   Title  \
0                              NaN     NaN
1                      Photography    Host
2                       Technology  Member
3                                   Member
4                       Technology  Member
..                             ...     ...
711  Electrical Mechanical Service  Member
712                                 Member
713                                 Member
714                                 Member
715                                 Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
711                                                         Hulmeville, PA
712                                                                     NA
713                                                          Baltimore, MD
714                                                                     NA
715                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
711                                                 NA
712                                                 NA
713                                        Aquaculture
714                                                 NA
715                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
711                                  NA
712                                  NA
713                                  NA
714                                  NA
715                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
711                                                 NA
712                                                 NA
713                                                 NA
714                                                 NA
715                                                 NA

[716 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
712         Marvin Salazar     Marvin       Salazar               Member
713         Ariel Sokoloff      Ariel      Sokoloff               Member
714           Robert Dicks     Robert         Dicks               Member
715         Winston Carter    Winston        Carter               Member
716         Yerodin Prince    Yerodin        Prince               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
712                                                                     NA
713                                                          Baltimore, MD
714                                                                     NA
715                                                                     NA
716                                                           New York, NY

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
712                                                 NA
713                                        Aquaculture
714                                                 NA
715                                                 NA
716                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
712                                  NA
713                                  NA
714                                  NA
715                                  NA
716                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
712                                                 NA
713                                                 NA
714                                                 NA
715                                                 NA
716                                                 NA

[717 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
713         Ariel Sokoloff      Ariel      Sokoloff               Member
714           Robert Dicks     Robert         Dicks               Member
715         Winston Carter    Winston        Carter               Member
716         Yerodin Prince    Yerodin        Prince               Member
717              Wasi Reza       Wasi          Reza               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
713                                                          Baltimore, MD
714                                                                     NA
715                                                                     NA
716                                                           New York, NY
717                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
713                                        Aquaculture
714                                                 NA
715                                                 NA
716                                                 NA
717                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
713                                  NA
714                                  NA
715                                  NA
716                                  NA
717                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
713                                                 NA
714                                                 NA
715                                                 NA
716                                                 NA
717                                                 NA

[718 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
714           Robert Dicks     Robert         Dicks               Member
715         Winston Carter    Winston        Carter               Member
716         Yerodin Prince    Yerodin        Prince               Member
717              Wasi Reza       Wasi          Reza               Member
718          Istvan Csergo     Istvan        Csergo               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
714                                                                     NA
715                                                                     NA
716                                                           New York, NY
717                                                                     NA
718                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
714                                                 NA
715                                                 NA
716                                                 NA
717                                                 NA
718                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
714                                  NA
715                                  NA
716                                  NA
717                                  NA
718                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
714                                                 NA
715                                                 NA
716                                                 NA
717                                                 NA
718                                                 NA

[719 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
715         Winston Carter    Winston        Carter               Member
716         Yerodin Prince    Yerodin        Prince               Member
717              Wasi Reza       Wasi          Reza               Member
718          Istvan Csergo     Istvan        Csergo               Member
719          Sadiel Jarvis     Sadiel        Jarvis   Technology  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
715                                                                     NA
716                                                           New York, NY
717                                                                     NA
718                                                                     NA
719                                                      Pompano Beach, FL

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
715                                                 NA
716                                                 NA
717                                                 NA
718                                                 NA
719                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
715                                  NA
716                                  NA
717                                  NA
718                                  NA
719                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
715                                                 NA
716                                                 NA
717                                                 NA
718                                                 NA
719                                                 NA

[720 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
716         Yerodin Prince    Yerodin        Prince               Member
717              Wasi Reza       Wasi          Reza               Member
718          Istvan Csergo     Istvan        Csergo               Member
719          Sadiel Jarvis     Sadiel        Jarvis   Technology  Member
720           Randy Parson      Randy        Parson               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
716                                                           New York, NY
717                                                                     NA
718                                                                     NA
719                                                      Pompano Beach, FL
720                                                            Norfolk, VA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
716                                                 NA
717                                                 NA
718                                                 NA
719                                                 NA
720                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
716                                  NA
717                                  NA
718                                  NA
719                                  NA
720                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
716                                                 NA
717                                                 NA
718                                                 NA
719                                                 NA
720                                                 NA

[721 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
717              Wasi Reza       Wasi          Reza               Member
718          Istvan Csergo     Istvan        Csergo               Member
719          Sadiel Jarvis     Sadiel        Jarvis   Technology  Member
720           Randy Parson      Randy        Parson               Member
721             Aryeh Thau      Aryeh          Thau               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
717                                                                     NA
718                                                                     NA
719                                                      Pompano Beach, FL
720                                                            Norfolk, VA
721                                                      Jerusalem, Israel

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
717                                                 NA
718                                                 NA
719                                                 NA
720                                                 NA
721                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
717                                  NA
718                                  NA
719                                  NA
720                                  NA
721                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
717                                                 NA
718                                                 NA
719                                                 NA
720                                                 NA
721                                                 NA

[722 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
718          Istvan Csergo     Istvan        Csergo               Member
719          Sadiel Jarvis     Sadiel        Jarvis   Technology  Member
720           Randy Parson      Randy        Parson               Member
721             Aryeh Thau      Aryeh          Thau               Member
722      Benjamin Braganza   Benjamin      Braganza               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
718                                                                     NA
719                                                      Pompano Beach, FL
720                                                            Norfolk, VA
721                                                      Jerusalem, Israel
722                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
718                                                 NA
719                                                 NA
720                                                 NA
721                                                 NA
722                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
718                                  NA
719                                  NA
720                                  NA
721                                  NA
722                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
718                                                 NA
719                                                 NA
720                                                 NA
721                                                 NA
722                                                 NA

[723 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
719          Sadiel Jarvis     Sadiel        Jarvis   Technology  Member
720           Randy Parson      Randy        Parson               Member
721             Aryeh Thau      Aryeh          Thau               Member
722      Benjamin Braganza   Benjamin      Braganza               Member
723           Brett Denton      Brett        Denton               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
719                                                      Pompano Beach, FL
720                                                            Norfolk, VA
721                                                      Jerusalem, Israel
722                                                                     NA
723                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
719                                                 NA
720                                                 NA
721                                                 NA
722                                                 NA
723                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
719                                  NA
720                                  NA
721                                  NA
722                                  NA
723                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
719                                                 NA
720                                                 NA
721                                                 NA
722                                                 NA
723                                                 NA

[724 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
720           Randy Parson      Randy        Parson               Member
721             Aryeh Thau      Aryeh          Thau               Member
722      Benjamin Braganza   Benjamin      Braganza               Member
723           Brett Denton      Brett        Denton               Member
724         Amine Bennouna      Amine      Bennouna               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
720                                                            Norfolk, VA
721                                                      Jerusalem, Israel
722                                                                     NA
723                                                                     NA
724                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
720                                                 NA
721                                                 NA
722                                                 NA
723                                                 NA
724  I'm an investor looking to acquire my first bu...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
720                                  NA
721                                  NA
722                                  NA
723                                  NA
724                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
720                                                 NA
721                                                 NA
722                                                 NA
723                                                 NA
724                                                 NA

[725 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
721             Aryeh Thau      Aryeh          Thau               Member
722      Benjamin Braganza   Benjamin      Braganza               Member
723           Brett Denton      Brett        Denton               Member
724         Amine Bennouna      Amine      Bennouna               Member
725           Daniel Caleb     Daniel         Caleb      Fashion  Member

                                                 About             Location  \
0                                                  NaN                  NaN
1    l'm Angela and here to help you succeed. l am ...           Marion, TX
2    I have over 15+ years in project management. I...                   NA
3        I'm part of the team here at Acquisitions.com    San Francisco, CA
4    25+ years of expertise as business owner Most ...   Boisbriand, Canada
..                                                 ...                  ...
721                                                       Jerusalem, Israel
722                                                                      NA
723                                                                      NA
724                                                                      NA
725                                                     Geneva, Switzerland

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
721                                                 NA
722                                                 NA
723                                                 NA
724  I'm an investor looking to acquire my first bu...
725                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
721                                  NA
722                                  NA
723                                  NA
724                                  NA
725                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
721                                                 NA
722                                                 NA
723                                                 NA
724                                                 NA
725                                                 NA

[726 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
722      Benjamin Braganza   Benjamin      Braganza               Member
723           Brett Denton      Brett        Denton               Member
724         Amine Bennouna      Amine      Bennouna               Member
725           Daniel Caleb     Daniel         Caleb      Fashion  Member
726        Foti Vazanellis       Foti    Vazanellis               Member

                                                 About             Location  \
0                                                  NaN                  NaN
1    l'm Angela and here to help you succeed. l am ...           Marion, TX
2    I have over 15+ years in project management. I...                   NA
3        I'm part of the team here at Acquisitions.com    San Francisco, CA
4    25+ years of expertise as business owner Most ...   Boisbriand, Canada
..                                                 ...                  ...
722                                                                      NA
723                                                                      NA
724                                                                      NA
725                                                     Geneva, Switzerland
726                                                     Brisbane, Australia

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
722                                                 NA
723                                                 NA
724  I'm an investor looking to acquire my first bu...
725                                                 NA
726                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
722                                  NA
723                                  NA
724                                  NA
725                                  NA
726                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
722                                                 NA
723                                                 NA
724                                                 NA
725                                                 NA
726                                                 NA

[727 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
723           Brett Denton      Brett        Denton               Member
724         Amine Bennouna      Amine      Bennouna               Member
725           Daniel Caleb     Daniel         Caleb      Fashion  Member
726        Foti Vazanellis       Foti    Vazanellis               Member
727           Valon Islami      Valon        Islami               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
723
724
725
726
727

                                    Location  \
0                                        NaN
1                                 Marion, TX
2                                         NA
3                          San Francisco, CA
4                         Boisbriand, Canada
..                                       ...
723                                       NA
724                                       NA
725                      Geneva, Switzerland
726                      Brisbane, Australia
727  Skopje, F. Yugoslav Repub. Of Macedonia

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
723                                                 NA
724  I'm an investor looking to acquire my first bu...
725                                                 NA
726                                                 NA
727                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
723                                  NA
724                                  NA
725                                  NA
726                                  NA
727                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
723                                                 NA
724                                                 NA
725                                                 NA
726                                                 NA
727                                                 NA

[728 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
724         Amine Bennouna      Amine      Bennouna               Member
725           Daniel Caleb     Daniel         Caleb      Fashion  Member
726        Foti Vazanellis       Foti    Vazanellis               Member
727           Valon Islami      Valon        Islami               Member
728         Aaron Sadowski      Aaron      Sadowski               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
724
725
726
727
728

                                    Location  \
0                                        NaN
1                                 Marion, TX
2                                         NA
3                          San Francisco, CA
4                         Boisbriand, Canada
..                                       ...
724                                       NA
725                      Geneva, Switzerland
726                      Brisbane, Australia
727  Skopje, F. Yugoslav Repub. Of Macedonia
728                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
724  I'm an investor looking to acquire my first bu...
725                                                 NA
726                                                 NA
727                                                 NA
728                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
724                                  NA
725                                  NA
726                                  NA
727                                  NA
728                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
724                                                 NA
725                                                 NA
726                                                 NA
727                                                 NA
728                                                 NA

[729 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
725           Daniel Caleb     Daniel         Caleb        Fashion  Member
726        Foti Vazanellis       Foti    Vazanellis                 Member
727           Valon Islami      Valon        Islami                 Member
728         Aaron Sadowski      Aaron      Sadowski                 Member
729          Siobhan Evans    Siobhan         Evans  Manufacturing  Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
725
726
727
728
729

                                    Location  \
0                                        NaN
1                                 Marion, TX
2                                         NA
3                          San Francisco, CA
4                         Boisbriand, Canada
..                                       ...
725                      Geneva, Switzerland
726                      Brisbane, Australia
727  Skopje, F. Yugoslav Repub. Of Macedonia
728                                       NA
729                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
725                                                 NA
726                                                 NA
727                                                 NA
728                                                 NA
729                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
725                                  NA
726                                  NA
727                                  NA
728                                  NA
729                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
725                                                 NA
726                                                 NA
727                                                 NA
728                                                 NA
729                                                 NA

[730 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
726        Foti Vazanellis       Foti    Vazanellis                 Member
727           Valon Islami      Valon        Islami                 Member
728         Aaron Sadowski      Aaron      Sadowski                 Member
729          Siobhan Evans    Siobhan         Evans  Manufacturing  Member
730               Mo Moosa         Mo         Moosa                 Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
726
727
728
729
730

                                    Location  \
0                                        NaN
1                                 Marion, TX
2                                         NA
3                          San Francisco, CA
4                         Boisbriand, Canada
..                                       ...
726                      Brisbane, Australia
727  Skopje, F. Yugoslav Repub. Of Macedonia
728                                       NA
729                                       NA
730                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
726                                                 NA
727                                                 NA
728                                                 NA
729                                                 NA
730                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
726                                  NA
727                                  NA
728                                  NA
729                                  NA
730                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
726                                                 NA
727                                                 NA
728                                                 NA
729                                                 NA
730                                                 NA

[731 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
727           Valon Islami      Valon        Islami                 Member
728         Aaron Sadowski      Aaron      Sadowski                 Member
729          Siobhan Evans    Siobhan         Evans  Manufacturing  Member
730               Mo Moosa         Mo         Moosa                 Member
731            John Santos       John        Santos                 Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
727
728
729
730
731

                                    Location  \
0                                        NaN
1                                 Marion, TX
2                                         NA
3                          San Francisco, CA
4                         Boisbriand, Canada
..                                       ...
727  Skopje, F. Yugoslav Repub. Of Macedonia
728                                       NA
729                                       NA
730                                       NA
731                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
727                                                 NA
728                                                 NA
729                                                 NA
730                                                 NA
731                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
727                                  NA
728                                  NA
729                                  NA
730                                  NA
731                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
727                                                 NA
728                                                 NA
729                                                 NA
730                                                 NA
731                                                 NA

[732 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
728         Aaron Sadowski      Aaron      Sadowski                 Member
729          Siobhan Evans    Siobhan         Evans  Manufacturing  Member
730               Mo Moosa         Mo         Moosa                 Member
731            John Santos       John        Santos                 Member
732         Jeremy Sanders     Jeremy       Sanders                 Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
728                                                                     NA
729                                                                     NA
730                                                                     NA
731                                                                     NA
732                                                         Huntsville, AL

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
728                                                 NA
729                                                 NA
730                                                 NA
731                                                 NA
732                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
728                                  NA
729                                  NA
730                                  NA
731                                  NA
732                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
728                                                 NA
729                                                 NA
730                                                 NA
731                                                 NA
732                                                 NA

[733 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name       Industry   Title  \
0                      NaN        NaN           NaN            NaN     NaN
1                 Angela P     Angela             P    Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay     Technology  Member
3                 Friz Ela       Friz           Ela                 Member
4           Pascal Germain     Pascal       Germain     Technology  Member
..                     ...        ...           ...            ...     ...
729          Siobhan Evans    Siobhan         Evans  Manufacturing  Member
730               Mo Moosa         Mo         Moosa                 Member
731            John Santos       John        Santos                 Member
732         Jeremy Sanders     Jeremy       Sanders                 Member
733             Orane Cole      Orane          Cole                 Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
729                                                                     NA
730                                                                     NA
731                                                                     NA
732                                                         Huntsville, AL
733                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
729                                                 NA
730                                                 NA
731                                                 NA
732                                                 NA
733                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
729                                  NA
730                                  NA
731                                  NA
732                                  NA
733                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
729                                                 NA
730                                                 NA
731                                                 NA
732                                                 NA
733                                                 NA

[734 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
730               Mo Moosa         Mo         Moosa               Member
731            John Santos       John        Santos               Member
732         Jeremy Sanders     Jeremy       Sanders               Member
733             Orane Cole      Orane          Cole               Member
734             Trevor Cho     Trevor           Cho               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
730                                                                     NA
731                                                                     NA
732                                                         Huntsville, AL
733                                                                     NA
734                                                      Moreno Valley, CA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
730                                                 NA
731                                                 NA
732                                                 NA
733                                                 NA
734                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
730                                  NA
731                                  NA
732                                  NA
733                                  NA
734                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
730                                                 NA
731                                                 NA
732                                                 NA
733                                                 NA
734                                                 NA

[735 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
731            John Santos       John        Santos               Member
732         Jeremy Sanders     Jeremy       Sanders               Member
733             Orane Cole      Orane          Cole               Member
734             Trevor Cho     Trevor           Cho               Member
735           Peyman Parsi     Peyman         Parsi               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
731
732
733
734
735

                             Location  \
0                                 NaN
1                          Marion, TX
2                                  NA
3                   San Francisco, CA
4                  Boisbriand, Canada
..                                ...
731                                NA
732                    Huntsville, AL
733                                NA
734                 Moreno Valley, CA
735  North Vancouver District, Canada

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
731                                                 NA
732                                                 NA
733                                                 NA
734                                                 NA
735                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
731                                  NA
732                                  NA
733                                  NA
734                                  NA
735                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
731                                                 NA
732                                                 NA
733                                                 NA
734                                                 NA
735                                                 NA

[736 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
732         Jeremy Sanders     Jeremy       Sanders               Member
733             Orane Cole      Orane          Cole               Member
734             Trevor Cho     Trevor           Cho               Member
735           Peyman Parsi     Peyman         Parsi               Member
736           Malik Turner      Malik        Turner               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
732
733
734
735
736

                             Location  \
0                                 NaN
1                          Marion, TX
2                                  NA
3                   San Francisco, CA
4                  Boisbriand, Canada
..                                ...
732                    Huntsville, AL
733                                NA
734                 Moreno Valley, CA
735  North Vancouver District, Canada
736                                NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
732                                                 NA
733                                                 NA
734                                                 NA
735                                                 NA
736                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
732                                  NA
733                                  NA
734                                  NA
735                                  NA
736                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
732                                                 NA
733                                                 NA
734                                                 NA
735                                                 NA
736                                                 NA

[737 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
733             Orane Cole      Orane          Cole               Member
734             Trevor Cho     Trevor           Cho               Member
735           Peyman Parsi     Peyman         Parsi               Member
736           Malik Turner      Malik        Turner               Member
737           Glenn Hudson      Glenn        Hudson               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
733
734
735
736
737

                             Location  \
0                                 NaN
1                          Marion, TX
2                                  NA
3                   San Francisco, CA
4                  Boisbriand, Canada
..                                ...
733                                NA
734                 Moreno Valley, CA
735  North Vancouver District, Canada
736                                NA
737                      Gwinnett, GA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
733                                                 NA
734                                                 NA
735                                                 NA
736                                                 NA
737                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
733                                  NA
734                                  NA
735                                  NA
736                                  NA
737                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
733                                                 NA
734                                                 NA
735                                                 NA
736                                                 NA
737                                                 NA

[738 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
734             Trevor Cho     Trevor           Cho               Member
735           Peyman Parsi     Peyman         Parsi               Member
736           Malik Turner      Malik        Turner               Member
737           Glenn Hudson      Glenn        Hudson               Member
738          Joe Bvumburai        Joe     Bvumburai               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
734
735
736
737
738

                             Location  \
0                                 NaN
1                          Marion, TX
2                                  NA
3                   San Francisco, CA
4                  Boisbriand, Canada
..                                ...
734                 Moreno Valley, CA
735  North Vancouver District, Canada
736                                NA
737                      Gwinnett, GA
738                                NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
734                                                 NA
735                                                 NA
736                                                 NA
737                                                 NA
738                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
734                                  NA
735                                  NA
736                                  NA
737                                  NA
738                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
734                                                 NA
735                                                 NA
736                                                 NA
737                                                 NA
738                                                 NA

[739 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
735           Peyman Parsi     Peyman         Parsi               Member
736           Malik Turner      Malik        Turner               Member
737           Glenn Hudson      Glenn        Hudson               Member
738          Joe Bvumburai        Joe     Bvumburai               Member
739           Ram Djagovar        Ram      Djagovar   Healthcare  Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
735
736
737
738
739

                             Location  \
0                                 NaN
1                          Marion, TX
2                                  NA
3                   San Francisco, CA
4                  Boisbriand, Canada
..                                ...
735  North Vancouver District, Canada
736                                NA
737                      Gwinnett, GA
738                                NA
739         Edinburgh, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
735                                                 NA
736                                                 NA
737                                                 NA
738                                                 NA
739                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
735                                  NA
736                                  NA
737                                  NA
738                                  NA
739                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
735                                                 NA
736                                                 NA
737                                                 NA
738                                                 NA
739                                                 NA

[740 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
736           Malik Turner      Malik        Turner               Member
737           Glenn Hudson      Glenn        Hudson               Member
738          Joe Bvumburai        Joe     Bvumburai               Member
739           Ram Djagovar        Ram      Djagovar   Healthcare  Member
740       Patrick Anderson    Patrick      Anderson               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
736
737
738
739
740

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
736                         NA
737               Gwinnett, GA
738                         NA
739  Edinburgh, United Kingdom
740          Kodiak Island, AK

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
736                                                 NA
737                                                 NA
738                                                 NA
739                                                 NA
740                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
736                                  NA
737                                  NA
738                                  NA
739                                  NA
740                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
736                                                 NA
737                                                 NA
738                                                 NA
739                                                 NA
740                                                 NA

[741 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name               Industry  \
0                      NaN        NaN           NaN                    NaN
1                 Angela P     Angela             P            Photography
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay             Technology
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain             Technology
..                     ...        ...           ...                    ...
737           Glenn Hudson      Glenn        Hudson
738          Joe Bvumburai        Joe     Bvumburai
739           Ram Djagovar        Ram      Djagovar             Healthcare
740       Patrick Anderson    Patrick      Anderson
741         Gavin Fletcher      Gavin      Fletcher  Facilities Management

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
737  Member
738  Member
739  Member
740  Member
741  Member

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
737               Gwinnett, GA
738                         NA
739  Edinburgh, United Kingdom
740          Kodiak Island, AK
741                         NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
737                                                 NA
738                                                 NA
739                                                 NA
740                                                 NA
741                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
737                                  NA
738                                  NA
739                                  NA
740                                  NA
741                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
737                                                 NA
738                                                 NA
739                                                 NA
740                                                 NA
741                                                 NA

[742 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name               Industry  \
0                      NaN        NaN           NaN                    NaN
1                 Angela P     Angela             P            Photography
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay             Technology
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain             Technology
..                     ...        ...           ...                    ...
738          Joe Bvumburai        Joe     Bvumburai
739           Ram Djagovar        Ram      Djagovar             Healthcare
740       Patrick Anderson    Patrick      Anderson
741         Gavin Fletcher      Gavin      Fletcher  Facilities Management
742         Ayoub EL HYONI      Ayoub         HYONI

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
738  Member
739  Member
740  Member
741  Member
742  Member

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
738                         NA
739  Edinburgh, United Kingdom
740          Kodiak Island, AK
741                         NA
742                         NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
738                                                 NA
739                                                 NA
740                                                 NA
741                                                 NA
742                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
738                                  NA
739                                  NA
740                                  NA
741                                  NA
742                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
738                                                 NA
739                                                 NA
740                                                 NA
741                                                 NA
742                                                 NA

[743 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name               Industry  \
0                      NaN        NaN           NaN                    NaN
1                 Angela P     Angela             P            Photography
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay             Technology
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain             Technology
..                     ...        ...           ...                    ...
739           Ram Djagovar        Ram      Djagovar             Healthcare
740       Patrick Anderson    Patrick      Anderson
741         Gavin Fletcher      Gavin      Fletcher  Facilities Management
742         Ayoub EL HYONI      Ayoub         HYONI
743            Luis Rivera       Luis        Rivera

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
739  Member
740  Member
741  Member
742  Member
743  Member

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
739  Edinburgh, United Kingdom
740          Kodiak Island, AK
741                         NA
742                         NA
743               Brooklyn, MD

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
739                                                 NA
740                                                 NA
741                                                 NA
742                                                 NA
743                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
739                                  NA
740                                  NA
741                                  NA
742                                  NA
743                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
739                                                 NA
740                                                 NA
741                                                 NA
742                                                 NA
743                                                 NA

[744 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name               Industry  \
0                      NaN        NaN           NaN                    NaN
1                 Angela P     Angela             P            Photography
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay             Technology
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain             Technology
..                     ...        ...           ...                    ...
740       Patrick Anderson    Patrick      Anderson
741         Gavin Fletcher      Gavin      Fletcher  Facilities Management
742         Ayoub EL HYONI      Ayoub         HYONI
743            Luis Rivera       Luis        Rivera
744      Boris van der lem      Boris           lem              Ecommerce

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
740  Member
741  Member
742  Member
743  Member
744  Member

               Location                                              Intro  \
0                   NaN                                                NaN
1            Marion, TX  Hi Everyone I had a business that l started fr...
2                    NA                                                 NA
3     San Francisco, CA                                                 NA
4    Boisbriand, Canada  Investor + Business Aquisition + Business Opti...
..                  ...                                                ...
740   Kodiak Island, AK                                                 NA
741                  NA                                                 NA
742                  NA                                                 NA
743        Brooklyn, MD                                                 NA
744       Goch, Germany  Hello, I've just turned 30, and willing to be ...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
740                                  NA
741                                  NA
742                                  NA
743                                  NA
744                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
740                                                 NA
741                                                 NA
742                                                 NA
743                                                 NA
744                                                 NA

[745 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name               Industry  \
0                      NaN        NaN           NaN                    NaN
1                 Angela P     Angela             P            Photography
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay             Technology
3                 Friz Ela       Friz           Ela
4           Pascal Germain     Pascal       Germain             Technology
..                     ...        ...           ...                    ...
741         Gavin Fletcher      Gavin      Fletcher  Facilities Management
742         Ayoub EL HYONI      Ayoub         HYONI
743            Luis Rivera       Luis        Rivera
744      Boris van der lem      Boris           lem              Ecommerce
745         William Nesbit    William        Nesbit

      Title                                              About  \
0       NaN                                                NaN
1      Host  l'm Angela and here to help you succeed. l am ...
2    Member  I have over 15+ years in project management. I...
3    Member      I'm part of the team here at Acquisitions.com
4    Member  25+ years of expertise as business owner Most ...
..      ...                                                ...
741  Member
742  Member
743  Member
744  Member
745  Member

               Location                                              Intro  \
0                   NaN                                                NaN
1            Marion, TX  Hi Everyone I had a business that l started fr...
2                    NA                                                 NA
3     San Francisco, CA                                                 NA
4    Boisbriand, Canada  Investor + Business Aquisition + Business Opti...
..                  ...                                                ...
741                  NA                                                 NA
742                  NA                                                 NA
743        Brooklyn, MD                                                 NA
744       Goch, Germany  Hello, I've just turned 30, and willing to be ...
745                  NA                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
741                                  NA
742                                  NA
743                                  NA
744                                  NA
745                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
741                                                 NA
742                                                 NA
743                                                 NA
744                                                 NA
745                                                 NA

[746 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
742         Ayoub EL HYONI      Ayoub         HYONI               Member
743            Luis Rivera       Luis        Rivera               Member
744      Boris van der lem      Boris           lem    Ecommerce  Member
745         William Nesbit    William        Nesbit               Member
746          Jose Guarnido       Jose      Guarnido               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
742                                                                     NA
743                                                           Brooklyn, MD
744                                                          Goch, Germany
745                                                                     NA
746                                                       Barcelona, Spain

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
742                                                 NA
743                                                 NA
744  Hello, I've just turned 30, and willing to be ...
745                                                 NA
746              Big 4 auditor. M&A in Hotel industry.

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
742                                  NA
743                                  NA
744                                  NA
745                                  NA
746                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
742                                                 NA
743                                                 NA
744                                                 NA
745                                                 NA
746                                                 NA

[747 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
743            Luis Rivera       Luis        Rivera               Member
744      Boris van der lem      Boris           lem    Ecommerce  Member
745         William Nesbit    William        Nesbit               Member
746          Jose Guarnido       Jose      Guarnido               Member
747           Nyasha Nhari     Nyasha         Nhari               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
743
744
745
746
747

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
743             Brooklyn, MD
744            Goch, Germany
745                       NA
746         Barcelona, Spain
747  Bristol, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
743                                                 NA
744  Hello, I've just turned 30, and willing to be ...
745                                                 NA
746              Big 4 auditor. M&A in Hotel industry.
747                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
743                                  NA
744                                  NA
745                                  NA
746                                  NA
747                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
743                                                 NA
744                                                 NA
745                                                 NA
746                                                 NA
747                                                 NA

[748 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
744      Boris van der lem      Boris           lem    Ecommerce  Member
745         William Nesbit    William        Nesbit               Member
746          Jose Guarnido       Jose      Guarnido               Member
747           Nyasha Nhari     Nyasha         Nhari               Member
748              Samy Yaga       Samy          Yaga               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
744
745
746
747
748

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
744            Goch, Germany
745                       NA
746         Barcelona, Spain
747  Bristol, United Kingdom
748        Lent, Netherlands

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
744  Hello, I've just turned 30, and willing to be ...
745                                                 NA
746              Big 4 auditor. M&A in Hotel industry.
747                                                 NA
748                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
744                                  NA
745                                  NA
746                                  NA
747                                  NA
748                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
744                                                 NA
745                                                 NA
746                                                 NA
747                                                 NA
748                                                 NA

[749 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
745         William Nesbit    William        Nesbit               Member
746          Jose Guarnido       Jose      Guarnido               Member
747           Nyasha Nhari     Nyasha         Nhari               Member
748              Samy Yaga       Samy          Yaga               Member
749             Jeff Crane       Jeff         Crane               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
745
746
747
748
749

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
745                       NA
746         Barcelona, Spain
747  Bristol, United Kingdom
748        Lent, Netherlands
749                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
745                                                 NA
746              Big 4 auditor. M&A in Hotel industry.
747                                                 NA
748                                                 NA
749                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
745                                  NA
746                                  NA
747                                  NA
748                                  NA
749                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
745                                                 NA
746                                                 NA
747                                                 NA
748                                                 NA
749                                                 NA

[750 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
746          Jose Guarnido       Jose      Guarnido               Member
747           Nyasha Nhari     Nyasha         Nhari               Member
748              Samy Yaga       Samy          Yaga               Member
749             Jeff Crane       Jeff         Crane               Member
750           Darius Saheb     Darius         Saheb   Technology  Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
746
747
748
749
750

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
746         Barcelona, Spain
747  Bristol, United Kingdom
748        Lent, Netherlands
749                       NA
750        Vancouver, Canada

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
746              Big 4 auditor. M&A in Hotel industry.
747                                                 NA
748                                                 NA
749                                                 NA
750                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
746                                  NA
747                                  NA
748                                  NA
749                                  NA
750                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
746                                                 NA
747                                                 NA
748                                                 NA
749                                                 NA
750                                                 NA

[751 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
747           Nyasha Nhari     Nyasha         Nhari               Member
748              Samy Yaga       Samy          Yaga               Member
749             Jeff Crane       Jeff         Crane               Member
750           Darius Saheb     Darius         Saheb   Technology  Member
751            Ven Mummadi        Ven       Mummadi   Technology  Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
747
748
749
750
751

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
747  Bristol, United Kingdom
748        Lent, Netherlands
749                       NA
750        Vancouver, Canada
751                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
747                                                 NA
748                                                 NA
749                                                 NA
750                                                 NA
751                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
747                                  NA
748                                  NA
749                                  NA
750                                  NA
751                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
747                                                 NA
748                                                 NA
749                                                 NA
750                                                 NA
751                                                 NA

[752 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
748              Samy Yaga       Samy          Yaga               Member
749             Jeff Crane       Jeff         Crane               Member
750           Darius Saheb     Darius         Saheb   Technology  Member
751            Ven Mummadi        Ven       Mummadi   Technology  Member
752      Christal Phillips   Christal      Phillips               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
748                                                      Lent, Netherlands
749                                                                     NA
750                                                      Vancouver, Canada
751                                                                     NA
752                                                             Newark, NJ

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
748                                                 NA
749                                                 NA
750                                                 NA
751                                                 NA
752                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
748                                  NA
749                                  NA
750                                  NA
751                                  NA
752                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
748                                                 NA
749                                                 NA
750                                                 NA
751                                                 NA
752                                                 NA

[753 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
749             Jeff Crane       Jeff         Crane               Member
750           Darius Saheb     Darius         Saheb   Technology  Member
751            Ven Mummadi        Ven       Mummadi   Technology  Member
752      Christal Phillips   Christal      Phillips               Member
753           Aram Taghavi       Aram       Taghavi               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
749                                                                     NA
750                                                      Vancouver, Canada
751                                                                     NA
752                                                             Newark, NJ
753                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
749                                                 NA
750                                                 NA
751                                                 NA
752                                                 NA
753                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
749                                  NA
750                                  NA
751                                  NA
752                                  NA
753                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
749                                                 NA
750                                                 NA
751                                                 NA
752                                                 NA
753                                                 NA

[754 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
750           Darius Saheb     Darius         Saheb   Technology  Member
751            Ven Mummadi        Ven       Mummadi   Technology  Member
752      Christal Phillips   Christal      Phillips               Member
753           Aram Taghavi       Aram       Taghavi               Member
754          Trishul Patel    Trishul         Patel               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
750                                                      Vancouver, Canada
751                                                                     NA
752                                                             Newark, NJ
753                                                                     NA
754                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
750                                                 NA
751                                                 NA
752                                                 NA
753                                                 NA
754                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
750                                  NA
751                                  NA
752                                  NA
753                                  NA
754                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
750                                                 NA
751                                                 NA
752                                                 NA
753                                                 NA
754                                                 NA

[755 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
751            Ven Mummadi        Ven       Mummadi   Technology  Member
752      Christal Phillips   Christal      Phillips               Member
753           Aram Taghavi       Aram       Taghavi               Member
754          Trishul Patel    Trishul         Patel               Member
755     Adetunji Adaraloye   Adetunji     Adaraloye               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
751                                                                     NA
752                                                             Newark, NJ
753                                                                     NA
754                                                                     NA
755                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
751                                                 NA
752                                                 NA
753                                                 NA
754                                                 NA
755                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
751                                  NA
752                                  NA
753                                  NA
754                                  NA
755                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
751                                                 NA
752                                                 NA
753                                                 NA
754                                                 NA
755                                                 NA

[756 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
752      Christal Phillips   Christal      Phillips               Member
753           Aram Taghavi       Aram       Taghavi               Member
754          Trishul Patel    Trishul         Patel               Member
755     Adetunji Adaraloye   Adetunji     Adaraloye               Member
756           Miguel Silva     Miguel         Silva               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
752                                                             Newark, NJ
753                                                                     NA
754                                                                     NA
755                                                                     NA
756                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
752                                                 NA
753                                                 NA
754                                                 NA
755                                                 NA
756                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
752                                  NA
753                                  NA
754                                  NA
755                                  NA
756                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
752                                                 NA
753                                                 NA
754                                                 NA
755                                                 NA
756                                                 NA

[757 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
753           Aram Taghavi       Aram       Taghavi               Member
754          Trishul Patel    Trishul         Patel               Member
755     Adetunji Adaraloye   Adetunji     Adaraloye               Member
756           Miguel Silva     Miguel         Silva               Member
757          Cris Alvarado       Cris      Alvarado               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
753                                                                     NA
754                                                                     NA
755                                                                     NA
756                                                                     NA
757                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
753                                                 NA
754                                                 NA
755                                                 NA
756                                                 NA
757                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
753                                  NA
754                                  NA
755                                  NA
756                                  NA
757                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
753                                                 NA
754                                                 NA
755                                                 NA
756                                                 NA
757                                                 NA

[758 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
754          Trishul Patel    Trishul         Patel               Member
755     Adetunji Adaraloye   Adetunji     Adaraloye               Member
756           Miguel Silva     Miguel         Silva               Member
757          Cris Alvarado       Cris      Alvarado               Member
758             Gian Mejia       Gian         Mejia               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
754                                                                     NA
755                                                                     NA
756                                                                     NA
757                                                                     NA
758                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
754                                                 NA
755                                                 NA
756                                                 NA
757                                                 NA
758                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
754                                  NA
755                                  NA
756                                  NA
757                                  NA
758                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
754                                                 NA
755                                                 NA
756                                                 NA
757                                                 NA
758                                                 NA

[759 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
755     Adetunji Adaraloye   Adetunji     Adaraloye               Member
756           Miguel Silva     Miguel         Silva               Member
757          Cris Alvarado       Cris      Alvarado               Member
758             Gian Mejia       Gian         Mejia               Member
759            Steven Wang     Steven          Wang               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
755                                                                     NA
756                                                                     NA
757                                                                     NA
758                                                                     NA
759                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
755                                                 NA
756                                                 NA
757                                                 NA
758                                                 NA
759                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
755                                  NA
756                                  NA
757                                  NA
758                                  NA
759                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
755                                                 NA
756                                                 NA
757                                                 NA
758                                                 NA
759                                                 NA

[760 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
756           Miguel Silva     Miguel         Silva               Member
757          Cris Alvarado       Cris      Alvarado               Member
758             Gian Mejia       Gian         Mejia               Member
759            Steven Wang     Steven          Wang               Member
760      William Shekarian    William     Shekarian               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
756                                                                     NA
757                                                                     NA
758                                                                     NA
759                                                                     NA
760                                                         Louisville, KY

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
756                                                 NA
757                                                 NA
758                                                 NA
759                                                 NA
760                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
756                                  NA
757                                  NA
758                                  NA
759                                  NA
760                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
756                                                 NA
757                                                 NA
758                                                 NA
759                                                 NA
760                                                 NA

[761 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
757          Cris Alvarado       Cris      Alvarado               Member
758             Gian Mejia       Gian         Mejia               Member
759            Steven Wang     Steven          Wang               Member
760      William Shekarian    William     Shekarian               Member
761           Zak Mustapha        Zak      Mustapha               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
757
758
759
760
761

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
757                         NA
758                         NA
759                         NA
760             Louisville, KY
761  Edinburgh, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
757                                                 NA
758                                                 NA
759                                                 NA
760                                                 NA
761                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
757                                  NA
758                                  NA
759                                  NA
760                                  NA
761                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
757                                                 NA
758                                                 NA
759                                                 NA
760                                                 NA
761                                                 NA

[762 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
758             Gian Mejia       Gian         Mejia               Member
759            Steven Wang     Steven          Wang               Member
760      William Shekarian    William     Shekarian               Member
761           Zak Mustapha        Zak      Mustapha               Member
762              Sean Kyes       Sean          Kyes               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
758
759
760
761
762

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
758                         NA
759                         NA
760             Louisville, KY
761  Edinburgh, United Kingdom
762               San Jose, CA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
758                                                 NA
759                                                 NA
760                                                 NA
761                                                 NA
762                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
758                                  NA
759                                  NA
760                                  NA
761                                  NA
762                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
758                                                 NA
759                                                 NA
760                                                 NA
761                                                 NA
762                                                 NA

[763 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
759            Steven Wang     Steven          Wang               Member
760      William Shekarian    William     Shekarian               Member
761           Zak Mustapha        Zak      Mustapha               Member
762              Sean Kyes       Sean          Kyes               Member
763            Matt Currie       Matt        Currie               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
759
760
761
762
763

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
759                         NA
760             Louisville, KY
761  Edinburgh, United Kingdom
762               San Jose, CA
763                         NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
759                                                 NA
760                                                 NA
761                                                 NA
762                                                 NA
763                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
759                                  NA
760                                  NA
761                                  NA
762                                  NA
763                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
759                                                 NA
760                                                 NA
761                                                 NA
762                                                 NA
763                                                 NA

[764 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
760      William Shekarian    William     Shekarian               Member
761           Zak Mustapha        Zak      Mustapha               Member
762              Sean Kyes       Sean          Kyes               Member
763            Matt Currie       Matt        Currie               Member
764             ben dupree        ben        dupree               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
760
761
762
763
764

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
760             Louisville, KY
761  Edinburgh, United Kingdom
762               San Jose, CA
763                         NA
764                         NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
760                                                 NA
761                                                 NA
762                                                 NA
763                                                 NA
764                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
760                                  NA
761                                  NA
762                                  NA
763                                  NA
764                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
760                                                 NA
761                                                 NA
762                                                 NA
763                                                 NA
764                                                 NA

[765 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
761           Zak Mustapha        Zak      Mustapha               Member
762              Sean Kyes       Sean          Kyes               Member
763            Matt Currie       Matt        Currie               Member
764             ben dupree        ben        dupree               Member
765           Ethan French      Ethan        French               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
761
762
763
764
765

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
761  Edinburgh, United Kingdom
762               San Jose, CA
763                         NA
764                         NA
765                         NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
761                                                 NA
762                                                 NA
763                                                 NA
764                                                 NA
765                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
761                                  NA
762                                  NA
763                                  NA
764                                  NA
765                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
761                                                 NA
762                                                 NA
763                                                 NA
764                                                 NA
765                                                 NA

[766 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
762              Sean Kyes       Sean          Kyes               Member
763            Matt Currie       Matt        Currie               Member
764             ben dupree        ben        dupree               Member
765           Ethan French      Ethan        French               Member
766           Jason Gordon      Jason        Gordon               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
762                                                           San Jose, CA
763                                                                     NA
764                                                                     NA
765                                                                     NA
766                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
762                                                 NA
763                                                 NA
764                                                 NA
765                                                 NA
766                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
762                                  NA
763                                  NA
764                                  NA
765                                  NA
766                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
762                                                 NA
763                                                 NA
764                                                 NA
765                                                 NA
766                                                 NA

[767 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
763            Matt Currie       Matt        Currie               Member
764             ben dupree        ben        dupree               Member
765           Ethan French      Ethan        French               Member
766           Jason Gordon      Jason        Gordon               Member
767        Emily-Ann Okine  Emily-Ann         Okine               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
763                                                                     NA
764                                                                     NA
765                                                                     NA
766                                                                     NA
767                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
763                                                 NA
764                                                 NA
765                                                 NA
766                                                 NA
767                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
763                                  NA
764                                  NA
765                                  NA
766                                  NA
767                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
763                                                 NA
764                                                 NA
765                                                 NA
766                                                 NA
767                                                 NA

[768 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
764             ben dupree        ben        dupree               Member
765           Ethan French      Ethan        French               Member
766           Jason Gordon      Jason        Gordon               Member
767        Emily-Ann Okine  Emily-Ann         Okine               Member
768         Bryce Anderson      Bryce      Anderson               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
764                                                                     NA
765                                                                     NA
766                                                                     NA
767                                                                     NA
768                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
764                                                 NA
765                                                 NA
766                                                 NA
767                                                 NA
768                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
764                                  NA
765                                  NA
766                                  NA
767                                  NA
768                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
764                                                 NA
765                                                 NA
766                                                 NA
767                                                 NA
768                                                 NA

[769 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
765           Ethan French      Ethan        French                Member
766           Jason Gordon      Jason        Gordon                Member
767        Emily-Ann Okine  Emily-Ann         Okine                Member
768         Bryce Anderson      Bryce      Anderson                Member
769               Kia Paya        Kia          Paya  Construction  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
765                                                                     NA
766                                                                     NA
767                                                                     NA
768                                                                     NA
769  As a Contracts Administrator with over 14 year...   Sydney, Australia

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
765                                                 NA
766                                                 NA
767                                                 NA
768                                                 NA
769  I am a Civil Engineer with 14 years of experie...

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
765                                  NA
766                                  NA
767                                  NA
768                                  NA
769                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
765                                                 NA
766                                                 NA
767                                                 NA
768                                                 NA
769               https://www.linkedin.com/in/kiapaya/

[770 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
766           Jason Gordon      Jason        Gordon                Member
767        Emily-Ann Okine  Emily-Ann         Okine                Member
768         Bryce Anderson      Bryce      Anderson                Member
769               Kia Paya        Kia          Paya  Construction  Member
770        richard calvert    richard       calvert                Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
766                                                                     NA
767                                                                     NA
768                                                                     NA
769  As a Contracts Administrator with over 14 year...   Sydney, Australia
770                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
766                                                 NA
767                                                 NA
768                                                 NA
769  I am a Civil Engineer with 14 years of experie...
770                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
766                                  NA
767                                  NA
768                                  NA
769                                  NA
770                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
766                                                 NA
767                                                 NA
768                                                 NA
769               https://www.linkedin.com/in/kiapaya/
770                                                 NA

[771 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
767        Emily-Ann Okine  Emily-Ann         Okine                Member
768         Bryce Anderson      Bryce      Anderson                Member
769               Kia Paya        Kia          Paya  Construction  Member
770        richard calvert    richard       calvert                Member
771           Rajneesh Jha   Rajneesh           Jha                Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
767                                                                     NA
768                                                                     NA
769  As a Contracts Administrator with over 14 year...   Sydney, Australia
770                                                                     NA
771                                                               Caln, PA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
767                                                 NA
768                                                 NA
769  I am a Civil Engineer with 14 years of experie...
770                                                 NA
771                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
767                                  NA
768                                  NA
769                                  NA
770                                  NA
771                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
767                                                 NA
768                                                 NA
769               https://www.linkedin.com/in/kiapaya/
770                                                 NA
771                                                 NA

[772 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
768         Bryce Anderson      Bryce      Anderson                Member
769               Kia Paya        Kia          Paya  Construction  Member
770        richard calvert    richard       calvert                Member
771           Rajneesh Jha   Rajneesh           Jha                Member
772           Said Alsaleh       Said       Alsaleh                Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
768                                                                     NA
769  As a Contracts Administrator with over 14 year...   Sydney, Australia
770                                                                     NA
771                                                               Caln, PA
772                                                             Summit, NJ

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
768                                                 NA
769  I am a Civil Engineer with 14 years of experie...
770                                                 NA
771                                                 NA
772                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
768                                  NA
769                                  NA
770                                  NA
771                                  NA
772                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
768                                                 NA
769               https://www.linkedin.com/in/kiapaya/
770                                                 NA
771                                                 NA
772                                                 NA

[773 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
769               Kia Paya        Kia          Paya  Construction  Member
770        richard calvert    richard       calvert                Member
771           Rajneesh Jha   Rajneesh           Jha                Member
772           Said Alsaleh       Said       Alsaleh                Member
773             Rick Rosen       Rick         Rosen                Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
769  As a Contracts Administrator with over 14 year...   Sydney, Australia
770                                                                     NA
771                                                               Caln, PA
772                                                             Summit, NJ
773                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
769  I am a Civil Engineer with 14 years of experie...
770                                                 NA
771                                                 NA
772                                                 NA
773                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
769                                  NA
770                                  NA
771                                  NA
772                                  NA
773                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
769               https://www.linkedin.com/in/kiapaya/
770                                                 NA
771                                                 NA
772                                                 NA
773                                                 NA

[774 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                     Full name First Name     Last Name     Industry   Title  \
0                          NaN        NaN           NaN          NaN     NaN
1                     Angela P     Angela             P  Photography    Host
2        Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                     Friz Ela       Friz           Ela               Member
4               Pascal Germain     Pascal       Germain   Technology  Member
..                         ...        ...           ...          ...     ...
770            richard calvert    richard       calvert               Member
771               Rajneesh Jha   Rajneesh           Jha               Member
772               Said Alsaleh       Said       Alsaleh               Member
773                 Rick Rosen       Rick         Rosen               Member
774  Alexander House Leicester  Alexander     Leicester               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
770                                                                     NA
771                                                               Caln, PA
772                                                             Summit, NJ
773                                                                     NA
774                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
770                                                 NA
771                                                 NA
772                                                 NA
773                                                 NA
774                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
770                                  NA
771                                  NA
772                                  NA
773                                  NA
774                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
770                                                 NA
771                                                 NA
772                                                 NA
773                                                 NA
774                                                 NA

[775 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                     Full name First Name     Last Name     Industry   Title  \
0                          NaN        NaN           NaN          NaN     NaN
1                     Angela P     Angela             P  Photography    Host
2        Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                     Friz Ela       Friz           Ela               Member
4               Pascal Germain     Pascal       Germain   Technology  Member
..                         ...        ...           ...          ...     ...
771               Rajneesh Jha   Rajneesh           Jha               Member
772               Said Alsaleh       Said       Alsaleh               Member
773                 Rick Rosen       Rick         Rosen               Member
774  Alexander House Leicester  Alexander     Leicester               Member
775            Boniface Ogunti   Boniface        Ogunti               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
771                                                               Caln, PA
772                                                             Summit, NJ
773                                                                     NA
774                                                                     NA
775                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
771                                                 NA
772                                                 NA
773                                                 NA
774                                                 NA
775                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
771                                  NA
772                                  NA
773                                  NA
774                                  NA
775                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
771                                                 NA
772                                                 NA
773                                                 NA
774                                                 NA
775                                                 NA

[776 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                     Full name First Name     Last Name     Industry   Title  \
0                          NaN        NaN           NaN          NaN     NaN
1                     Angela P     Angela             P  Photography    Host
2        Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                     Friz Ela       Friz           Ela               Member
4               Pascal Germain     Pascal       Germain   Technology  Member
..                         ...        ...           ...          ...     ...
772               Said Alsaleh       Said       Alsaleh               Member
773                 Rick Rosen       Rick         Rosen               Member
774  Alexander House Leicester  Alexander     Leicester               Member
775            Boniface Ogunti   Boniface        Ogunti               Member
776                 Dion Jones       Dion         Jones               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
772                                                             Summit, NJ
773                                                                     NA
774                                                                     NA
775                                                                     NA
776                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
772                                                 NA
773                                                 NA
774                                                 NA
775                                                 NA
776                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
772                                  NA
773                                  NA
774                                  NA
775                                  NA
776                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
772                                                 NA
773                                                 NA
774                                                 NA
775                                                 NA
776                                                 NA

[777 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                     Full name First Name     Last Name     Industry   Title  \
0                          NaN        NaN           NaN          NaN     NaN
1                     Angela P     Angela             P  Photography    Host
2        Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                     Friz Ela       Friz           Ela               Member
4               Pascal Germain     Pascal       Germain   Technology  Member
..                         ...        ...           ...          ...     ...
773                 Rick Rosen       Rick         Rosen               Member
774  Alexander House Leicester  Alexander     Leicester               Member
775            Boniface Ogunti   Boniface        Ogunti               Member
776                 Dion Jones       Dion         Jones               Member
777                Burk Wegner       Burk        Wegner               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
773                                                                     NA
774                                                                     NA
775                                                                     NA
776                                                                     NA
777                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
773                                                 NA
774                                                 NA
775                                                 NA
776                                                 NA
777                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
773                                  NA
774                                  NA
775                                  NA
776                                  NA
777                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
773                                                 NA
774                                                 NA
775                                                 NA
776                                                 NA
777                                                 NA

[778 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                     Full name First Name     Last Name     Industry   Title  \
0                          NaN        NaN           NaN          NaN     NaN
1                     Angela P     Angela             P  Photography    Host
2        Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                     Friz Ela       Friz           Ela               Member
4               Pascal Germain     Pascal       Germain   Technology  Member
..                         ...        ...           ...          ...     ...
774  Alexander House Leicester  Alexander     Leicester               Member
775            Boniface Ogunti   Boniface        Ogunti               Member
776                 Dion Jones       Dion         Jones               Member
777                Burk Wegner       Burk        Wegner               Member
778               Jorge Rangel      Jorge        Rangel               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
774                                                                     NA
775                                                                     NA
776                                                                     NA
777                                                                     NA
778                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
774                                                 NA
775                                                 NA
776                                                 NA
777                                                 NA
778                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
774                                  NA
775                                  NA
776                                  NA
777                                  NA
778                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
774                                                 NA
775                                                 NA
776                                                 NA
777                                                 NA
778                                                 NA

[779 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
775        Boniface Ogunti   Boniface        Ogunti               Member
776             Dion Jones       Dion         Jones               Member
777            Burk Wegner       Burk        Wegner               Member
778           Jorge Rangel      Jorge        Rangel               Member
779          Aaron Sandvig      Aaron       Sandvig               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
775                                                                     NA
776                                                                     NA
777                                                                     NA
778                                                                     NA
779                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
775                                                 NA
776                                                 NA
777                                                 NA
778                                                 NA
779                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
775                                  NA
776                                  NA
777                                  NA
778                                  NA
779                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
775                                                 NA
776                                                 NA
777                                                 NA
778                                                 NA
779                                                 NA

[780 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
776             Dion Jones       Dion         Jones               Member
777            Burk Wegner       Burk        Wegner               Member
778           Jorge Rangel      Jorge        Rangel               Member
779          Aaron Sandvig      Aaron       Sandvig               Member
780          Suhail Shaikh     Suhail        Shaikh               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
776                                                                     NA
777                                                                     NA
778                                                                     NA
779                                                                     NA
780                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
776                                                 NA
777                                                 NA
778                                                 NA
779                                                 NA
780                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
776                                  NA
777                                  NA
778                                  NA
779                                  NA
780                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
776                                                 NA
777                                                 NA
778                                                 NA
779                                                 NA
780                                                 NA

[781 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
777            Burk Wegner       Burk        Wegner               Member
778           Jorge Rangel      Jorge        Rangel               Member
779          Aaron Sandvig      Aaron       Sandvig               Member
780          Suhail Shaikh     Suhail        Shaikh               Member
781            matt tenney       matt        tenney               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
777                                                                     NA
778                                                                     NA
779                                                                     NA
780                                                                     NA
781                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
777                                                 NA
778                                                 NA
779                                                 NA
780                                                 NA
781                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
777                                  NA
778                                  NA
779                                  NA
780                                  NA
781                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
777                                                 NA
778                                                 NA
779                                                 NA
780                                                 NA
781                                                 NA

[782 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
778           Jorge Rangel      Jorge        Rangel               Member
779          Aaron Sandvig      Aaron       Sandvig               Member
780          Suhail Shaikh     Suhail        Shaikh               Member
781            matt tenney       matt        tenney               Member
782             Steve Bird      Steve          Bird               Member

                                                 About              Location  \
0                                                  NaN                   NaN
1    l'm Angela and here to help you succeed. l am ...            Marion, TX
2    I have over 15+ years in project management. I...                    NA
3        I'm part of the team here at Acquisitions.com     San Francisco, CA
4    25+ years of expertise as business owner Most ...    Boisbriand, Canada
..                                                 ...                   ...
778                                                                       NA
779                                                                       NA
780                                                                       NA
781                                                                       NA
782                                                     Kent, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
778                                                 NA
779                                                 NA
780                                                 NA
781                                                 NA
782                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
778                                  NA
779                                  NA
780                                  NA
781                                  NA
782                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
778                                                 NA
779                                                 NA
780                                                 NA
781                                                 NA
782                                                 NA

[783 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
779          Aaron Sandvig      Aaron       Sandvig               Member
780          Suhail Shaikh     Suhail        Shaikh               Member
781            matt tenney       matt        tenney               Member
782             Steve Bird      Steve          Bird               Member
783         piotr zarudzki      piotr      zarudzki               Member

                                                 About              Location  \
0                                                  NaN                   NaN
1    l'm Angela and here to help you succeed. l am ...            Marion, TX
2    I have over 15+ years in project management. I...                    NA
3        I'm part of the team here at Acquisitions.com     San Francisco, CA
4    25+ years of expertise as business owner Most ...    Boisbriand, Canada
..                                                 ...                   ...
779                                                                       NA
780                                                                       NA
781                                                                       NA
782                                                     Kent, United Kingdom
783                                                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
779                                                 NA
780                                                 NA
781                                                 NA
782                                                 NA
783                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
779                                  NA
780                                  NA
781                                  NA
782                                  NA
783                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
779                                                 NA
780                                                 NA
781                                                 NA
782                                                 NA
783                                                 NA

[784 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
780          Suhail Shaikh     Suhail        Shaikh               Member
781            matt tenney       matt        tenney               Member
782             Steve Bird      Steve          Bird               Member
783         piotr zarudzki      piotr      zarudzki               Member
784           Grant Eagles      Grant        Eagles               Member

                                                 About              Location  \
0                                                  NaN                   NaN
1    l'm Angela and here to help you succeed. l am ...            Marion, TX
2    I have over 15+ years in project management. I...                    NA
3        I'm part of the team here at Acquisitions.com     San Francisco, CA
4    25+ years of expertise as business owner Most ...    Boisbriand, Canada
..                                                 ...                   ...
780                                                                       NA
781                                                                       NA
782                                                     Kent, United Kingdom
783                                                                       NA
784                                                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
780                                                 NA
781                                                 NA
782                                                 NA
783                                                 NA
784                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
780                                  NA
781                                  NA
782                                  NA
783                                  NA
784         http://www.khemiagroup.com/

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
780                                                 NA
781                                                 NA
782                                                 NA
783                                                 NA
784                                                 NA

[785 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
781            matt tenney       matt        tenney               Member
782             Steve Bird      Steve          Bird               Member
783         piotr zarudzki      piotr      zarudzki               Member
784           Grant Eagles      Grant        Eagles               Member
785             Chris Kern      Chris          Kern               Member

                                                 About              Location  \
0                                                  NaN                   NaN
1    l'm Angela and here to help you succeed. l am ...            Marion, TX
2    I have over 15+ years in project management. I...                    NA
3        I'm part of the team here at Acquisitions.com     San Francisco, CA
4    25+ years of expertise as business owner Most ...    Boisbriand, Canada
..                                                 ...                   ...
781                                                                       NA
782                                                     Kent, United Kingdom
783                                                                       NA
784                                                                       NA
785                                                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
781                                                 NA
782                                                 NA
783                                                 NA
784                                                 NA
785                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
781                                  NA
782                                  NA
783                                  NA
784         http://www.khemiagroup.com/
785                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
781                                                 NA
782                                                 NA
783                                                 NA
784                                                 NA
785                                                 NA

[786 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
782             Steve Bird      Steve          Bird               Member
783         piotr zarudzki      piotr      zarudzki               Member
784           Grant Eagles      Grant        Eagles               Member
785             Chris Kern      Chris          Kern               Member
786                Sho Vue        Sho           Vue               Member

                                                 About              Location  \
0                                                  NaN                   NaN
1    l'm Angela and here to help you succeed. l am ...            Marion, TX
2    I have over 15+ years in project management. I...                    NA
3        I'm part of the team here at Acquisitions.com     San Francisco, CA
4    25+ years of expertise as business owner Most ...    Boisbriand, Canada
..                                                 ...                   ...
782                                                     Kent, United Kingdom
783                                                                       NA
784                                                                       NA
785                                                                       NA
786                                                                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
782                                                 NA
783                                                 NA
784                                                 NA
785                                                 NA
786                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
782                                  NA
783                                  NA
784         http://www.khemiagroup.com/
785                                  NA
786                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
782                                                 NA
783                                                 NA
784                                                 NA
785                                                 NA
786                                                 NA

[787 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
783         piotr zarudzki      piotr      zarudzki               Member
784           Grant Eagles      Grant        Eagles               Member
785             Chris Kern      Chris          Kern               Member
786                Sho Vue        Sho           Vue               Member
787           Kevin Meehan      Kevin        Meehan               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
783                                                                     NA
784                                                                     NA
785                                                                     NA
786                                                                     NA
787                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
783                                                 NA
784                                                 NA
785                                                 NA
786                                                 NA
787                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
783                                  NA
784         http://www.khemiagroup.com/
785                                  NA
786                                  NA
787                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
783                                                 NA
784                                                 NA
785                                                 NA
786                                                 NA
787                                                 NA

[788 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
784           Grant Eagles      Grant        Eagles               Member
785             Chris Kern      Chris          Kern               Member
786                Sho Vue        Sho           Vue               Member
787           Kevin Meehan      Kevin        Meehan               Member
788             Jack Brear       Jack         Brear               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
784                                                                     NA
785                                                                     NA
786                                                                     NA
787                                                                     NA
788                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
784                                                 NA
785                                                 NA
786                                                 NA
787                                                 NA
788                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
784         http://www.khemiagroup.com/
785                                  NA
786                                  NA
787                                  NA
788                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
784                                                 NA
785                                                 NA
786                                                 NA
787                                                 NA
788                                                 NA

[789 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
785             Chris Kern      Chris          Kern               Member
786                Sho Vue        Sho           Vue               Member
787           Kevin Meehan      Kevin        Meehan               Member
788             Jack Brear       Jack         Brear               Member
789             Krown Chiu      Krown          Chiu               Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
785                                                                        NA
786                                                                        NA
787                                                                        NA
788                                                                        NA
789                                                     Changhua City, Taiwan

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
785                                                 NA
786                                                 NA
787                                                 NA
788                                                 NA
789                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
785                                  NA
786                                  NA
787                                  NA
788                                  NA
789                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
785                                                 NA
786                                                 NA
787                                                 NA
788                                                 NA
789                                                 NA

[790 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
786                Sho Vue        Sho           Vue               Member
787           Kevin Meehan      Kevin        Meehan               Member
788             Jack Brear       Jack         Brear               Member
789             Krown Chiu      Krown          Chiu               Member
790          Eric Saulnier       Eric      Saulnier               Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
786                                                                        NA
787                                                                        NA
788                                                                        NA
789                                                     Changhua City, Taiwan
790                                                                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
786                                                 NA
787                                                 NA
788                                                 NA
789                                                 NA
790                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
786                                  NA
787                                  NA
788                                  NA
789                                  NA
790                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
786                                                 NA
787                                                 NA
788                                                 NA
789                                                 NA
790                                                 NA

[791 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
787           Kevin Meehan      Kevin        Meehan               Member
788             Jack Brear       Jack         Brear               Member
789             Krown Chiu      Krown          Chiu               Member
790          Eric Saulnier       Eric      Saulnier               Member
791        Delwin Campbell     Delwin      Campbell               Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
787                                                                        NA
788                                                                        NA
789                                                     Changhua City, Taiwan
790                                                                        NA
791                                                                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
787                                                 NA
788                                                 NA
789                                                 NA
790                                                 NA
791                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
787                                  NA
788                                  NA
789                                  NA
790                                  NA
791                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
787                                                 NA
788                                                 NA
789                                                 NA
790                                                 NA
791                                                 NA

[792 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
788             Jack Brear       Jack         Brear                Member
789             Krown Chiu      Krown          Chiu                Member
790          Eric Saulnier       Eric      Saulnier                Member
791        Delwin Campbell     Delwin      Campbell                Member
792       Jonathan Haggard   Jonathan       Haggard  Construction  Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
788                                                                        NA
789                                                     Changhua City, Taiwan
790                                                                        NA
791                                                                        NA
792                                                                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
788                                                 NA
789                                                 NA
790                                                 NA
791                                                 NA
792                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
788                                  NA
789                                  NA
790                                  NA
791                                  NA
792                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
788                                                 NA
789                                                 NA
790                                                 NA
791                                                 NA
792                                                 NA

[793 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
789             Krown Chiu      Krown          Chiu                Member
790          Eric Saulnier       Eric      Saulnier                Member
791        Delwin Campbell     Delwin      Campbell                Member
792       Jonathan Haggard   Jonathan       Haggard  Construction  Member
793        Marcel Moldovan     Marcel      Moldovan                Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
789                                                     Changhua City, Taiwan
790                                                                        NA
791                                                                        NA
792                                                                        NA
793                                                           Toronto, Canada

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
789                                                 NA
790                                                 NA
791                                                 NA
792                                                 NA
793                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
789                                  NA
790                                  NA
791                                  NA
792                                  NA
793                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
789                                                 NA
790                                                 NA
791                                                 NA
792                                                 NA
793                                                 NA

[794 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
790          Eric Saulnier       Eric      Saulnier                Member
791        Delwin Campbell     Delwin      Campbell                Member
792       Jonathan Haggard   Jonathan       Haggard  Construction  Member
793        Marcel Moldovan     Marcel      Moldovan                Member
794       Kristin Jennings    Kristin      Jennings                Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
790                                                                     NA
791                                                                     NA
792                                                                     NA
793                                                        Toronto, Canada
794                                                         Boca Raton, FL

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
790                                                 NA
791                                                 NA
792                                                 NA
793                                                 NA
794                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
790                                  NA
791                                  NA
792                                  NA
793                                  NA
794                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
790                                                 NA
791                                                 NA
792                                                 NA
793                                                 NA
794                                                 NA

[795 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
791        Delwin Campbell     Delwin      Campbell                Member
792       Jonathan Haggard   Jonathan       Haggard  Construction  Member
793        Marcel Moldovan     Marcel      Moldovan                Member
794       Kristin Jennings    Kristin      Jennings                Member
795             Gordon Mak     Gordon           Mak                Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
791
792
793
794
795

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
791                       NA
792                       NA
793          Toronto, Canada
794           Boca Raton, FL
795  Croydon, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
791                                                 NA
792                                                 NA
793                                                 NA
794                                                 NA
795                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
791                                  NA
792                                  NA
793                                  NA
794                                  NA
795                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
791                                                 NA
792                                                 NA
793                                                 NA
794                                                 NA
795                                                 NA

[796 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name         Last Name      Industry   Title  \
0                      NaN        NaN               NaN           NaN     NaN
1                 Angela P     Angela                 P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika      Khanthavixay    Technology  Member
3                 Friz Ela       Friz               Ela                Member
4           Pascal Germain     Pascal           Germain    Technology  Member
..                     ...        ...               ...           ...     ...
792       Jonathan Haggard   Jonathan           Haggard  Construction  Member
793        Marcel Moldovan     Marcel          Moldovan                Member
794       Kristin Jennings    Kristin          Jennings                Member
795             Gordon Mak     Gordon               Mak                Member
796   Pan Papagiannopoulos        Pan  Papagiannopoulos                Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
792
793
794
795
796

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
792                       NA
793          Toronto, Canada
794           Boca Raton, FL
795  Croydon, United Kingdom
796                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
792                                                 NA
793                                                 NA
794                                                 NA
795                                                 NA
796                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
792                                  NA
793                                  NA
794                                  NA
795                                  NA
796                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
792                                                 NA
793                                                 NA
794                                                 NA
795                                                 NA
796                                                 NA

[797 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name         Last Name     Industry   Title  \
0                      NaN        NaN               NaN          NaN     NaN
1                 Angela P     Angela                 P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika      Khanthavixay   Technology  Member
3                 Friz Ela       Friz               Ela               Member
4           Pascal Germain     Pascal           Germain   Technology  Member
..                     ...        ...               ...          ...     ...
793        Marcel Moldovan     Marcel          Moldovan               Member
794       Kristin Jennings    Kristin          Jennings               Member
795             Gordon Mak     Gordon               Mak               Member
796   Pan Papagiannopoulos        Pan  Papagiannopoulos               Member
797           Rushi Jagtap      Rushi            Jagtap   Technology  Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
793
794
795
796
797

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
793          Toronto, Canada
794           Boca Raton, FL
795  Croydon, United Kingdom
796                       NA
797          Toronto, Canada

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
793                                                 NA
794                                                 NA
795                                                 NA
796                                                 NA
797                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
793                                  NA
794                                  NA
795                                  NA
796                                  NA
797                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
793                                                 NA
794                                                 NA
795                                                 NA
796                                                 NA
797                                                 NA

[798 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name         Last Name     Industry   Title  \
0                      NaN        NaN               NaN          NaN     NaN
1                 Angela P     Angela                 P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika      Khanthavixay   Technology  Member
3                 Friz Ela       Friz               Ela               Member
4           Pascal Germain     Pascal           Germain   Technology  Member
..                     ...        ...               ...          ...     ...
794       Kristin Jennings    Kristin          Jennings               Member
795             Gordon Mak     Gordon               Mak               Member
796   Pan Papagiannopoulos        Pan  Papagiannopoulos               Member
797           Rushi Jagtap      Rushi            Jagtap   Technology  Member
798     Jonathan Rodriguez   Jonathan         Rodriguez               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
794
795
796
797
798

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
794           Boca Raton, FL
795  Croydon, United Kingdom
796                       NA
797          Toronto, Canada
798              Baytown, TX

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
794                                                 NA
795                                                 NA
796                                                 NA
797                                                 NA
798                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
794                                  NA
795                                  NA
796                                  NA
797                                  NA
798                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
794                                                 NA
795                                                 NA
796                                                 NA
797                                                 NA
798                                                 NA

[799 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name         Last Name     Industry   Title  \
0                      NaN        NaN               NaN          NaN     NaN
1                 Angela P     Angela                 P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika      Khanthavixay   Technology  Member
3                 Friz Ela       Friz               Ela               Member
4           Pascal Germain     Pascal           Germain   Technology  Member
..                     ...        ...               ...          ...     ...
795             Gordon Mak     Gordon               Mak               Member
796   Pan Papagiannopoulos        Pan  Papagiannopoulos               Member
797           Rushi Jagtap      Rushi            Jagtap   Technology  Member
798     Jonathan Rodriguez   Jonathan         Rodriguez               Member
799           Abner Coelho      Abner            Coelho               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
795
796
797
798
799

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
795  Croydon, United Kingdom
796                       NA
797          Toronto, Canada
798              Baytown, TX
799          San Antonio, TX

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
795                                                 NA
796                                                 NA
797                                                 NA
798                                                 NA
799                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
795                                  NA
796                                  NA
797                                  NA
798                                  NA
799                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
795                                                 NA
796                                                 NA
797                                                 NA
798                                                 NA
799                                                 NA

[800 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name         Last Name     Industry   Title  \
0                      NaN        NaN               NaN          NaN     NaN
1                 Angela P     Angela                 P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika      Khanthavixay   Technology  Member
3                 Friz Ela       Friz               Ela               Member
4           Pascal Germain     Pascal           Germain   Technology  Member
..                     ...        ...               ...          ...     ...
796   Pan Papagiannopoulos        Pan  Papagiannopoulos               Member
797           Rushi Jagtap      Rushi            Jagtap   Technology  Member
798     Jonathan Rodriguez   Jonathan         Rodriguez               Member
799           Abner Coelho      Abner            Coelho               Member
800        David Kosciusko      David         Kosciusko               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
796                                                                     NA
797                                                        Toronto, Canada
798                                                            Baytown, TX
799                                                        San Antonio, TX
800                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
796                                                 NA
797                                                 NA
798                                                 NA
799                                                 NA
800                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
796                                  NA
797                                  NA
798                                  NA
799                                  NA
800                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
796                                                 NA
797                                                 NA
798                                                 NA
799                                                 NA
800                                                 NA

[801 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
797           Rushi Jagtap      Rushi        Jagtap   Technology  Member
798     Jonathan Rodriguez   Jonathan     Rodriguez               Member
799           Abner Coelho      Abner        Coelho               Member
800        David Kosciusko      David     Kosciusko               Member
801                Biao Wu       Biao            Wu               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
797                                                        Toronto, Canada
798                                                            Baytown, TX
799                                                        San Antonio, TX
800                                                                     NA
801                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
797                                                 NA
798                                                 NA
799                                                 NA
800                                                 NA
801                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
797                                  NA
798                                  NA
799                                  NA
800                                  NA
801                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
797                                                 NA
798                                                 NA
799                                                 NA
800                                                 NA
801                                                 NA

[802 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
798     Jonathan Rodriguez   Jonathan     Rodriguez               Member
799           Abner Coelho      Abner        Coelho               Member
800        David Kosciusko      David     Kosciusko               Member
801                Biao Wu       Biao            Wu               Member
802           Sepp Mougnol       Sepp       Mougnol        sport  Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
798                                                               Baytown, TX
799                                                           San Antonio, TX
800                                                                        NA
801                                                                        NA
802                                                     Sorel-Moussel, France

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
798                                                 NA
799                                                 NA
800                                                 NA
801                                                 NA
802                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
798                                  NA
799                                  NA
800                                  NA
801                                  NA
802                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
798                                                 NA
799                                                 NA
800                                                 NA
801                                                 NA
802                                                 NA

[803 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
799           Abner Coelho      Abner        Coelho               Member
800        David Kosciusko      David     Kosciusko               Member
801                Biao Wu       Biao            Wu               Member
802           Sepp Mougnol       Sepp       Mougnol        sport  Member
803       Spencer Albrecht    Spencer      Albrecht               Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
799                                                           San Antonio, TX
800                                                                        NA
801                                                                        NA
802                                                     Sorel-Moussel, France
803                                                                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
799                                                 NA
800                                                 NA
801                                                 NA
802                                                 NA
803                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
799                                  NA
800                                  NA
801                                  NA
802                                  NA
803                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
799                                                 NA
800                                                 NA
801                                                 NA
802                                                 NA
803                                                 NA

[804 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
800        David Kosciusko      David     Kosciusko               Member
801                Biao Wu       Biao            Wu               Member
802           Sepp Mougnol       Sepp       Mougnol        sport  Member
803       Spencer Albrecht    Spencer      Albrecht               Member
804         Justin Wallace     Justin       Wallace   Consulting  Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
800                                                                        NA
801                                                                        NA
802                                                     Sorel-Moussel, France
803                                                                        NA
804                                                       Brisbane, Australia

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
800                                                 NA
801                                                 NA
802                                                 NA
803                                                 NA
804                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
800                                  NA
801                                  NA
802                                  NA
803                                  NA
804                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
800                                                 NA
801                                                 NA
802                                                 NA
803                                                 NA
804                                                 NA

[805 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
801                Biao Wu       Biao            Wu               Member
802           Sepp Mougnol       Sepp       Mougnol        sport  Member
803       Spencer Albrecht    Spencer      Albrecht               Member
804         Justin Wallace     Justin       Wallace   Consulting  Member
805          Naja Muhammad       Naja      Muhammad               Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
801                                                                        NA
802                                                     Sorel-Moussel, France
803                                                                        NA
804                                                       Brisbane, Australia
805                                                                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
801                                                 NA
802                                                 NA
803                                                 NA
804                                                 NA
805                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
801                                  NA
802                                  NA
803                                  NA
804                                  NA
805                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
801                                                 NA
802                                                 NA
803                                                 NA
804                                                 NA
805                                                 NA

[806 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
802           Sepp Mougnol       Sepp       Mougnol        sport  Member
803       Spencer Albrecht    Spencer      Albrecht               Member
804         Justin Wallace     Justin       Wallace   Consulting  Member
805          Naja Muhammad       Naja      Muhammad               Member
806            Shiraz Khan     Shiraz          Khan               Member

                                                 About               Location  \
0                                                  NaN                    NaN
1    l'm Angela and here to help you succeed. l am ...             Marion, TX
2    I have over 15+ years in project management. I...                     NA
3        I'm part of the team here at Acquisitions.com      San Francisco, CA
4    25+ years of expertise as business owner Most ...     Boisbriand, Canada
..                                                 ...                    ...
802                                                     Sorel-Moussel, France
803                                                                        NA
804                                                       Brisbane, Australia
805                                                                        NA
806                                                                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
802                                                 NA
803                                                 NA
804                                                 NA
805                                                 NA
806                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
802                                  NA
803                                  NA
804                                  NA
805                                  NA
806                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
802                                                 NA
803                                                 NA
804                                                 NA
805                                                 NA
806                                                 NA

[807 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
803       Spencer Albrecht    Spencer      Albrecht               Member
804         Justin Wallace     Justin       Wallace   Consulting  Member
805          Naja Muhammad       Naja      Muhammad               Member
806            Shiraz Khan     Shiraz          Khan               Member
807             Nixon Otim      Nixon          Otim               Member

                                                 About             Location  \
0                                                  NaN                  NaN
1    l'm Angela and here to help you succeed. l am ...           Marion, TX
2    I have over 15+ years in project management. I...                   NA
3        I'm part of the team here at Acquisitions.com    San Francisco, CA
4    25+ years of expertise as business owner Most ...   Boisbriand, Canada
..                                                 ...                  ...
803                                                                      NA
804                                                     Brisbane, Australia
805                                                                      NA
806                                                                      NA
807                                                                      NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
803                                                 NA
804                                                 NA
805                                                 NA
806                                                 NA
807                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
803                                  NA
804                                  NA
805                                  NA
806                                  NA
807                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
803                                                 NA
804                                                 NA
805                                                 NA
806                                                 NA
807                                                 NA

[808 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
804         Justin Wallace     Justin       Wallace   Consulting  Member
805          Naja Muhammad       Naja      Muhammad               Member
806            Shiraz Khan     Shiraz          Khan               Member
807             Nixon Otim      Nixon          Otim               Member
808         Jared Campbell      Jared      Campbell               Member

                                                 About             Location  \
0                                                  NaN                  NaN
1    l'm Angela and here to help you succeed. l am ...           Marion, TX
2    I have over 15+ years in project management. I...                   NA
3        I'm part of the team here at Acquisitions.com    San Francisco, CA
4    25+ years of expertise as business owner Most ...   Boisbriand, Canada
..                                                 ...                  ...
804                                                     Brisbane, Australia
805                                                                      NA
806                                                                      NA
807                                                                      NA
808                                                                      NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
804                                                 NA
805                                                 NA
806                                                 NA
807                                                 NA
808                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
804                                  NA
805                                  NA
806                                  NA
807                                  NA
808                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
804                                                 NA
805                                                 NA
806                                                 NA
807                                                 NA
808                                                 NA

[809 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
805          Naja Muhammad       Naja      Muhammad               Member
806            Shiraz Khan     Shiraz          Khan               Member
807             Nixon Otim      Nixon          Otim               Member
808         Jared Campbell      Jared      Campbell               Member
809          Paul Dupervil       Paul      Dupervil               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
805                                                                     NA
806                                                                     NA
807                                                                     NA
808                                                                     NA
809                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
805                                                 NA
806                                                 NA
807                                                 NA
808                                                 NA
809                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
805                                  NA
806                                  NA
807                                  NA
808                                  NA
809                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
805                                                 NA
806                                                 NA
807                                                 NA
808                                                 NA
809                                                 NA

[810 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
806            Shiraz Khan     Shiraz          Khan               Member
807             Nixon Otim      Nixon          Otim               Member
808         Jared Campbell      Jared      Campbell               Member
809          Paul Dupervil       Paul      Dupervil               Member
810           David Heston      David        Heston               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
806                                                                     NA
807                                                                     NA
808                                                                     NA
809                                                                     NA
810                                                      Coeur D'Alene, ID

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
806                                                 NA
807                                                 NA
808                                                 NA
809                                                 NA
810                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
806                                  NA
807                                  NA
808                                  NA
809                                  NA
810                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
806                                                 NA
807                                                 NA
808                                                 NA
809                                                 NA
810                                                 NA

[811 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
807             Nixon Otim      Nixon          Otim               Member
808         Jared Campbell      Jared      Campbell               Member
809          Paul Dupervil       Paul      Dupervil               Member
810           David Heston      David        Heston               Member
811        Napoleon Sheard   Napoleon        Sheard               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
807                                                                     NA
808                                                                     NA
809                                                                     NA
810                                                      Coeur D'Alene, ID
811                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
807                                                 NA
808                                                 NA
809                                                 NA
810                                                 NA
811                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
807                                  NA
808                                  NA
809                                  NA
810                                  NA
811                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
807                                                 NA
808                                                 NA
809                                                 NA
810                                                 NA
811                                                 NA

[812 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
808         Jared Campbell      Jared      Campbell               Member
809          Paul Dupervil       Paul      Dupervil               Member
810           David Heston      David        Heston               Member
811        Napoleon Sheard   Napoleon        Sheard               Member
812             Yuka Sakai       Yuka         Sakai               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
808                                                                     NA
809                                                                     NA
810                                                      Coeur D'Alene, ID
811                                                                     NA
812                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
808                                                 NA
809                                                 NA
810                                                 NA
811                                                 NA
812                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
808                                  NA
809                                  NA
810                                  NA
811                                  NA
812                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
808                                                 NA
809                                                 NA
810                                                 NA
811                                                 NA
812                                                 NA

[813 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
809          Paul Dupervil       Paul      Dupervil               Member
810           David Heston      David        Heston               Member
811        Napoleon Sheard   Napoleon        Sheard               Member
812             Yuka Sakai       Yuka         Sakai               Member
813            James Wells      James         Wells               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
809                                                                     NA
810                                                      Coeur D'Alene, ID
811                                                                     NA
812                                                                     NA
813                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
809                                                 NA
810                                                 NA
811                                                 NA
812                                                 NA
813                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
809                                  NA
810                                  NA
811                                  NA
812                                  NA
813                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
809                                                 NA
810                                                 NA
811                                                 NA
812                                                 NA
813                                                 NA

[814 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
810           David Heston      David        Heston               Member
811        Napoleon Sheard   Napoleon        Sheard               Member
812             Yuka Sakai       Yuka         Sakai               Member
813            James Wells      James         Wells               Member
814          Shaya Wilhelm      Shaya       Wilhelm       Retail  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
810                                                      Coeur D'Alene, ID
811                                                                     NA
812                                                                     NA
813                                                                     NA
814                                                             Boston, MA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
810                                                 NA
811                                                 NA
812                                                 NA
813                                                 NA
814                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
810                                  NA
811                                  NA
812                                  NA
813                                  NA
814                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
810                                                 NA
811                                                 NA
812                                                 NA
813                                                 NA
814                                                 NA

[815 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
811        Napoleon Sheard   Napoleon        Sheard               Member
812             Yuka Sakai       Yuka         Sakai               Member
813            James Wells      James         Wells               Member
814          Shaya Wilhelm      Shaya       Wilhelm       Retail  Member
815         SERIOJA GLORIE    SERIOJA        GLORIE   Consulting  Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
811                                                                     NA
812                                                                     NA
813                                                                     NA
814                                                             Boston, MA
815                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
811                                                 NA
812                                                 NA
813                                                 NA
814                                                 NA
815                        Www.DigitalGlobalNomads.Com

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
811                                  NA
812                                  NA
813                                  NA
814                                  NA
815                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
811                                                 NA
812                                                 NA
813                                                 NA
814                                                 NA
815                                                 NA

[816 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
812             Yuka Sakai       Yuka         Sakai               Member
813            James Wells      James         Wells               Member
814          Shaya Wilhelm      Shaya       Wilhelm       Retail  Member
815         SERIOJA GLORIE    SERIOJA        GLORIE   Consulting  Member
816             Sheen Ford      Sheen          Ford               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
812                                                                     NA
813                                                                     NA
814                                                             Boston, MA
815                                                                     NA
816                                                          Cleveland, OH

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
812                                                 NA
813                                                 NA
814                                                 NA
815                        Www.DigitalGlobalNomads.Com
816                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
812                                  NA
813                                  NA
814                                  NA
815                                  NA
816                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
812                                                 NA
813                                                 NA
814                                                 NA
815                                                 NA
816                                                 NA

[817 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
813            James Wells      James         Wells               Member
814          Shaya Wilhelm      Shaya       Wilhelm       Retail  Member
815         SERIOJA GLORIE    SERIOJA        GLORIE   Consulting  Member
816             Sheen Ford      Sheen          Ford               Member
817           Jose Aldrete       Jose       Aldrete               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
813                                                                     NA
814                                                             Boston, MA
815                                                                     NA
816                                                          Cleveland, OH
817                                                           Cheyenne, WY

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
813                                                 NA
814                                                 NA
815                        Www.DigitalGlobalNomads.Com
816                                                 NA
817                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
813                                  NA
814                                  NA
815                                  NA
816                                  NA
817                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
813                                                 NA
814                                                 NA
815                                                 NA
816                                                 NA
817                                                 NA

[818 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
814          Shaya Wilhelm      Shaya       Wilhelm       Retail  Member
815         SERIOJA GLORIE    SERIOJA        GLORIE   Consulting  Member
816             Sheen Ford      Sheen          Ford               Member
817           Jose Aldrete       Jose       Aldrete               Member
818             Sital Shah      Sital          Shah               Member

                                                 About            Location  \
0                                                  NaN                 NaN
1    l'm Angela and here to help you succeed. l am ...          Marion, TX
2    I have over 15+ years in project management. I...                  NA
3        I'm part of the team here at Acquisitions.com   San Francisco, CA
4    25+ years of expertise as business owner Most ...  Boisbriand, Canada
..                                                 ...                 ...
814                                                             Boston, MA
815                                                                     NA
816                                                          Cleveland, OH
817                                                           Cheyenne, WY
818                                                                     NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
814                                                 NA
815                        Www.DigitalGlobalNomads.Com
816                                                 NA
817                                                 NA
818                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
814                                  NA
815                                  NA
816                                  NA
817                                  NA
818                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
814                                                 NA
815                                                 NA
816                                                 NA
817                                                 NA
818                                                 NA

[819 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
815         SERIOJA GLORIE    SERIOJA        GLORIE   Consulting  Member
816             Sheen Ford      Sheen          Ford               Member
817           Jose Aldrete       Jose       Aldrete               Member
818             Sital Shah      Sital          Shah               Member
819        Yann Com Nougue       Yann        Nougue               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
815
816
817
818
819

                     Location  \
0                         NaN
1                  Marion, TX
2                          NA
3           San Francisco, CA
4          Boisbriand, Canada
..                        ...
815                        NA
816             Cleveland, OH
817              Cheyenne, WY
818                        NA
819  Levallois-Perret, France

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
815                        Www.DigitalGlobalNomads.Com
816                                                 NA
817                                                 NA
818                                                 NA
819                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
815                                  NA
816                                  NA
817                                  NA
818                                  NA
819                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
815                                                 NA
816                                                 NA
817                                                 NA
818                                                 NA
819                                                 NA

[820 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
816             Sheen Ford      Sheen          Ford               Member
817           Jose Aldrete       Jose       Aldrete               Member
818             Sital Shah      Sital          Shah               Member
819        Yann Com Nougue       Yann        Nougue               Member
820          Eddie Menacho      Eddie       Menacho               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
816
817
818
819
820

                     Location  \
0                         NaN
1                  Marion, TX
2                          NA
3           San Francisco, CA
4          Boisbriand, Canada
..                        ...
816             Cleveland, OH
817              Cheyenne, WY
818                        NA
819  Levallois-Perret, France
820                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
816                                                 NA
817                                                 NA
818                                                 NA
819                                                 NA
820                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
816                                  NA
817                                  NA
818                                  NA
819                                  NA
820                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
816                                                 NA
817                                                 NA
818                                                 NA
819                                                 NA
820                                                 NA

[821 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
817           Jose Aldrete       Jose       Aldrete               Member
818             Sital Shah      Sital          Shah               Member
819        Yann Com Nougue       Yann        Nougue               Member
820          Eddie Menacho      Eddie       Menacho               Member
821          Trevor Styles     Trevor        Styles               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
817
818
819
820
821

                     Location  \
0                         NaN
1                  Marion, TX
2                          NA
3           San Francisco, CA
4          Boisbriand, Canada
..                        ...
817              Cheyenne, WY
818                        NA
819  Levallois-Perret, France
820                        NA
821         Vancouver, Canada

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
817                                                 NA
818                                                 NA
819                                                 NA
820                                                 NA
821                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
817                                  NA
818                                  NA
819                                  NA
820                                  NA
821                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
817                                                 NA
818                                                 NA
819                                                 NA
820                                                 NA
821                                                 NA

[822 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
818             Sital Shah      Sital          Shah               Member
819        Yann Com Nougue       Yann        Nougue               Member
820          Eddie Menacho      Eddie       Menacho               Member
821          Trevor Styles     Trevor        Styles               Member
822          Razvan Vlonga     Razvan        Vlonga               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
818
819
820
821
822

                     Location  \
0                         NaN
1                  Marion, TX
2                          NA
3           San Francisco, CA
4          Boisbriand, Canada
..                        ...
818                        NA
819  Levallois-Perret, France
820                        NA
821         Vancouver, Canada
822                        NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
818                                                 NA
819                                                 NA
820                                                 NA
821                                                 NA
822                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
818                                  NA
819                                  NA
820                                  NA
821                                  NA
822                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
818                                                 NA
819                                                 NA
820                                                 NA
821                                                 NA
822                                                 NA

[823 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
819        Yann Com Nougue       Yann        Nougue               Member
820          Eddie Menacho      Eddie       Menacho               Member
821          Trevor Styles     Trevor        Styles               Member
822          Razvan Vlonga     Razvan        Vlonga               Member
823         Nicol Grigoras      Nicol      Grigoras               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
819
820
821
822
823

                     Location  \
0                         NaN
1                  Marion, TX
2                          NA
3           San Francisco, CA
4          Boisbriand, Canada
..                        ...
819  Levallois-Perret, France
820                        NA
821         Vancouver, Canada
822                        NA
823         Kishinev, Moldova

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
819                                                 NA
820                                                 NA
821                                                 NA
822                                                 NA
823                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
819                                  NA
820                                  NA
821                                  NA
822                                  NA
823                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
819                                                 NA
820                                                 NA
821                                                 NA
822                                                 NA
823                                                 NA

[824 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
820          Eddie Menacho      Eddie       Menacho               Member
821          Trevor Styles     Trevor        Styles               Member
822          Razvan Vlonga     Razvan        Vlonga               Member
823         Nicol Grigoras      Nicol      Grigoras               Member
824            Obi odigboh        Obi       odigboh               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
820
821
822
823
824

                   Location  \
0                       NaN
1                Marion, TX
2                        NA
3         San Francisco, CA
4        Boisbriand, Canada
..                      ...
820                      NA
821       Vancouver, Canada
822                      NA
823       Kishinev, Moldova
824  London, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
820                                                 NA
821                                                 NA
822                                                 NA
823                                                 NA
824                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
820                                  NA
821                                  NA
822                                  NA
823                                  NA
824                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
820                                                 NA
821                                                 NA
822                                                 NA
823                                                 NA
824                                                 NA

[825 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
821          Trevor Styles     Trevor        Styles               Member
822          Razvan Vlonga     Razvan        Vlonga               Member
823         Nicol Grigoras      Nicol      Grigoras               Member
824            Obi odigboh        Obi       odigboh               Member
825             Neel Gokul       Neel         Gokul               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
821
822
823
824
825

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
821          Vancouver, Canada
822                         NA
823          Kishinev, Moldova
824     London, United Kingdom
825  Lancaster, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
821                                                 NA
822                                                 NA
823                                                 NA
824                                                 NA
825                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
821                                  NA
822                                  NA
823                                  NA
824                                  NA
825                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
821                                                 NA
822                                                 NA
823                                                 NA
824                                                 NA
825                                                 NA

[826 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
822          Razvan Vlonga     Razvan        Vlonga               Member
823         Nicol Grigoras      Nicol      Grigoras               Member
824            Obi odigboh        Obi       odigboh               Member
825             Neel Gokul       Neel         Gokul               Member
826       Michael Stephens    Michael      Stephens               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
822
823
824
825
826

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
822                         NA
823          Kishinev, Moldova
824     London, United Kingdom
825  Lancaster, United Kingdom
826               Portland, OR

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
822                                                 NA
823                                                 NA
824                                                 NA
825                                                 NA
826                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
822                                  NA
823                                  NA
824                                  NA
825                                  NA
826                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
822                                                 NA
823                                                 NA
824                                                 NA
825                                                 NA
826                                                 NA

[827 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name     Industry   Title  \
0                      NaN        NaN           NaN          NaN     NaN
1                 Angela P     Angela             P  Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay   Technology  Member
3                 Friz Ela       Friz           Ela               Member
4           Pascal Germain     Pascal       Germain   Technology  Member
..                     ...        ...           ...          ...     ...
823         Nicol Grigoras      Nicol      Grigoras               Member
824            Obi odigboh        Obi       odigboh               Member
825             Neel Gokul       Neel         Gokul               Member
826       Michael Stephens    Michael      Stephens               Member
827            Eugene Boca     Eugene          Boca               Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
823
824
825
826
827

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
823          Kishinev, Moldova
824     London, United Kingdom
825  Lancaster, United Kingdom
826               Portland, OR
827     London, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
823                                                 NA
824                                                 NA
825                                                 NA
826                                                 NA
827                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
823                                  NA
824                                  NA
825                                  NA
826                                  NA
827                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
823                                                 NA
824                                                 NA
825                                                 NA
826                                                 NA
827                                                 NA

[828 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
824            Obi odigboh        Obi       odigboh                Member
825             Neel Gokul       Neel         Gokul                Member
826       Michael Stephens    Michael      Stephens                Member
827            Eugene Boca     Eugene          Boca                Member
828            john kaplan       john        kaplan  Construction  Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
824
825
826
827
828

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
824     London, United Kingdom
825  Lancaster, United Kingdom
826               Portland, OR
827     London, United Kingdom
828                 Dallas, TX

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
824                                                 NA
825                                                 NA
826                                                 NA
827                                                 NA
828                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
824                                  NA
825                                  NA
826                                  NA
827                                  NA
828                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
824                                                 NA
825                                                 NA
826                                                 NA
827                                                 NA
828                                                 NA

[829 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
825             Neel Gokul       Neel         Gokul                Member
826       Michael Stephens    Michael      Stephens                Member
827            Eugene Boca     Eugene          Boca                Member
828            john kaplan       john        kaplan  Construction  Member
829         Mohammad Badat   Mohammad         Badat                Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
825
826
827
828
829

                      Location  \
0                          NaN
1                   Marion, TX
2                           NA
3            San Francisco, CA
4           Boisbriand, Canada
..                         ...
825  Lancaster, United Kingdom
826               Portland, OR
827     London, United Kingdom
828                 Dallas, TX
829    Norwich, United Kingdom

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
825                                                 NA
826                                                 NA
827                                                 NA
828                                                 NA
829                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
825                                  NA
826                                  NA
827                                  NA
828                                  NA
829                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
825                                                 NA
826                                                 NA
827                                                 NA
828                                                 NA
829                                                 NA

[830 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
826       Michael Stephens    Michael      Stephens                Member
827            Eugene Boca     Eugene          Boca                Member
828            john kaplan       john        kaplan  Construction  Member
829         Mohammad Badat   Mohammad         Badat                Member
830           Thomas Limon     Thomas         Limon                Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
826
827
828
829
830

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
826             Portland, OR
827   London, United Kingdom
828               Dallas, TX
829  Norwich, United Kingdom
830           Las Cruces, NM

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
826                                                 NA
827                                                 NA
828                                                 NA
829                                                 NA
830                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
826                                  NA
827                                  NA
828                                  NA
829                                  NA
830                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
826                                                 NA
827                                                 NA
828                                                 NA
829                                                 NA
830                                                 NA

[831 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
827            Eugene Boca     Eugene          Boca                Member
828            john kaplan       john        kaplan  Construction  Member
829         Mohammad Badat   Mohammad         Badat                Member
830           Thomas Limon     Thomas         Limon                Member
831             Sathy Nada      Sathy          Nada                Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
827
828
829
830
831

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
827   London, United Kingdom
828               Dallas, TX
829  Norwich, United Kingdom
830           Las Cruces, NM
831                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
827                                                 NA
828                                                 NA
829                                                 NA
830                                                 NA
831                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
827                                  NA
828                                  NA
829                                  NA
830                                  NA
831                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
827                                                 NA
828                                                 NA
829                                                 NA
830                                                 NA
831                                                 NA

[832 rows x 10 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_4536\1333813044.py:50: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gc= gc.append(Dic, ignore_index=True)

                 Full name First Name     Last Name      Industry   Title  \
0                      NaN        NaN           NaN           NaN     NaN
1                 Angela P     Angela             P   Photography    Host
2    Kanhnika Khanthavixay   Kanhnika  Khanthavixay    Technology  Member
3                 Friz Ela       Friz           Ela                Member
4           Pascal Germain     Pascal       Germain    Technology  Member
..                     ...        ...           ...           ...     ...
828            john kaplan       john        kaplan  Construction  Member
829         Mohammad Badat   Mohammad         Badat                Member
830           Thomas Limon     Thomas         Limon                Member
831             Sathy Nada      Sathy          Nada                Member
832        Spencer Edwards    Spencer       Edwards                Member

                                                 About  \
0                                                  NaN
1    l'm Angela and here to help you succeed. l am ...
2    I have over 15+ years in project management. I...
3        I'm part of the team here at Acquisitions.com
4    25+ years of expertise as business owner Most ...
..                                                 ...
828
829
830
831
832

                    Location  \
0                        NaN
1                 Marion, TX
2                         NA
3          San Francisco, CA
4         Boisbriand, Canada
..                       ...
828               Dallas, TX
829  Norwich, United Kingdom
830           Las Cruces, NM
831                       NA
832                       NA

                                                 Intro  \
0                                                  NaN
1    Hi Everyone I had a business that l started fr...
2                                                   NA
3                                                   NA
4    Investor + Business Aquisition + Business Opti...
..                                                 ...
828                                                 NA
829                                                 NA
830                                                 NA
831                                                 NA
832                                                 NA

                           personal web  \
0                                   NaN
1    https://photographyforaliving.com/
2                                    NA
3                                    NA
4                                    NA
..                                  ...
828                                  NA
829                                  NA
830                                  NA
831                                  NA
832                                  NA

                                             Linked in
0                                                  NaN
1                                                   NA
2    https://www.linkedin.com/in/kanhnika-k-822517226/
3                                                   NA
4    https://www.linkedin.com/in/pascal-germain-9a5...
..                                                 ...
828                                                 NA
829                                                 NA
830                                                 NA
831                                                 NA
832                                                 NA

[833 rows x 10 columns]

In [106]:
gc.to_excel("Members.xlsx")

In [42]:
box[5].find_element(By.TAG_NAME,"a").click()

In [89]:
box[0].find_element(By.CSS_SELECTOR,'[class="member-list-item-location text-color-lighter"]').text

'Marion, TX'

In [57]:
driver.find_element(By.CSS_SELECTOR,'[data-original-title="Linkedin"]').get_attribute("href")

'https://www.linkedin.com/in/jasonjeffrey300/'

In [21]:
#about-header > div.about-header-row.waypoint-trigger.about-header-title-row > div > div.about-header-text-wrapper > div.info.modal-hide > div

'Pascal Germain'

In [26]:
first_name=name.text.split()[0]

In [27]:
first_name

'Pascal'

In [44]:
driver.find_element(By.CSS_SELECTOR,"#community-member-about > div:nth-child(1) > div > div.content").text

''

In [69]:
driver.find_element(By.CSS_SELECTOR,'#community-member-about > div:nth-child(1) > div > div.title > a').text

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#community-member-about > div:nth-child(1) > div > div.title > a"}
  (Session info: chrome=114.0.5735.199)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x009FA813+48355]
	(No symbol) [0x0098C4B1]
	(No symbol) [0x00895358]
	(No symbol) [0x008C09A5]
	(No symbol) [0x008C0B3B]
	(No symbol) [0x008EE232]
	(No symbol) [0x008DA784]
	(No symbol) [0x008EC922]
	(No symbol) [0x008DA536]
	(No symbol) [0x008B82DC]
	(No symbol) [0x008B93DD]
	GetHandleVerifier [0x00C5AABD+2539405]
	GetHandleVerifier [0x00C9A78F+2800735]
	GetHandleVerifier [0x00C9456C+2775612]
	GetHandleVerifier [0x00A851E0+616112]
	(No symbol) [0x00995F8C]
	(No symbol) [0x00992328]
	(No symbol) [0x0099240B]
	(No symbol) [0x00984FF7]
	BaseThreadInitThunk [0x76EB00C9+25]
	RtlGetAppContainerNamedObjectPath [0x77A77B4E+286]
	RtlGetAppContainerNamedObjectPath [0x77A77B1E+238]

In [ ]:
#community-member-about > div:nth-child(3) > div > div.content